/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InsAccordion {
        "defaultOpen": number;
        "initAccordion": () => Promise<void>;
        "menu": boolean;
    }
    interface InsAccordionItem {
        "active": boolean;
        "arrowActivated": boolean;
        "disabled": boolean;
        "heading": string;
        "icon": string;
        "link": string;
        "linkTarget": string;
    }
    interface InsAccordionLink {
        "active": boolean;
        "disabled": boolean;
        "icon": string;
        "label": string;
        "link": string;
        "linkTarget": string;
        "linkTitle": string;
    }
    interface InsAdmin {
    }
    interface InsBackdrop {
        "light": boolean;
    }
    interface InsBarChart {
        "categories": Array<any>;
        "chartData": Array<any>;
        "horizontal": boolean;
        "name": string;
        "stacked": boolean;
    }
    interface InsBreadcrumbs {
        "breadcrumbs": Array<any>;
        "updateCrumbs": (crumbs: any, noRedirect?: boolean) => Promise<void>;
    }
    interface InsButton {
        "color": string;
        "cursor": string;
        "data": string;
        "disabled": boolean;
        "dropdown": boolean;
        "icon": string;
        "label": string;
        "loading": boolean;
        "options": string;
        "outlined": boolean;
        "size": string;
        "solid": boolean;
        "textTransform": string;
        "type": string;
    }
    interface InsButtonGroup {
        "activeIndex": number;
        "activeOption": string;
        "color": string;
        "disabled": boolean;
        "getActiveOption": () => Promise<{ index: number; label: any; }>;
        "options": string;
        "setActiveOption": (option: any) => Promise<void>;
        "size": string;
    }
    interface InsCard {
        "noPadding": boolean;
        "outlined": boolean;
        "steady": boolean;
    }
    interface InsCarousel {
        "autoplay": boolean;
        "bindTo": string;
        "bodyText": string;
        "ctaColor": string;
        "ctaDisabled": boolean;
        "ctaLabel": string;
        "ctaLink": string;
        "ctaLinkTarget": string;
        "duration": number;
        "goTo": (slide: any) => Promise<void>;
        "heading": string;
        "height": string;
        "layout": number;
        "loop": boolean;
        "noCarouselButton": boolean;
        "noPagination": boolean;
        "perPage": number;
        "startIndex": number;
        "subHeading": string;
        "transition": number;
        "width": string;
    }
    interface InsChart {
        "generateColor": (color: any, count: any) => Promise<Highcharts.ColorType>;
        "renderChart": (options: any) => Promise<void>;
    }
    interface InsCheckbox {
        "checked": boolean;
        "disabled": boolean;
        "falseValue": string;
        "label": string;
        "name": string;
        "trueValue": string;
        "updateCheckState": (state: any) => Promise<void>;
        "value": string;
    }
    interface InsCheckboxCard {
        "disabled": boolean;
        "label": string;
        "name": string;
        "noPadding": boolean;
        "selected": boolean;
        "selectedColor": string;
        "tabOrder": string;
        "value": string;
    }
    interface InsContent {
    }
    interface InsCreditCard {
        "active": boolean;
        "brand": string;
        "expired": boolean;
        "expiryMonth": string;
        "expiryYear": string;
        "fullYear": boolean;
        "lastFour": string;
        "value": string;
    }
    interface InsDateTime {
        "disabled": boolean;
        "errorMessage": string;
        "format": string;
        "hasError": boolean;
        "icon": string;
        "label": string;
        "maxDate": string;
        "maxTime": string;
        "minDate": string;
        "minTime": string;
        "mode": string;
        "name": string;
        "noMeridiem": boolean;
        "placeholder": string;
        "readonly": boolean;
        "value": string;
    }
    interface InsDatepicker {
        "disabled": boolean;
        "errorMessage": string;
        "format": string;
        "hasError": boolean;
        "icon": string;
        "label": string;
        "maxDate": string;
        "minDate": string;
        "name": string;
        "placeholder": string;
        "readonly": boolean;
        "value": string;
    }
    interface InsDrawer {
        "backdropCanClose": boolean;
        "bordered": boolean;
        "customWidth": string;
        "icon": string;
        "isOpen": boolean;
        "label": string;
        "noPadding": boolean;
        "position": string;
        "setDrawerState": (status: any) => Promise<void>;
        "showCloseButton": boolean;
        "showHeader": boolean;
        "stickyHeader": boolean;
    }
    interface InsFilter {
        "closeDateFilter": () => Promise<void>;
        "dateFrom": string;
        "dateOpt": any;
        "dateTitle": any;
        "dateTo": string;
        "defaultDate": string;
        "getDate": () => Promise<"All" | { from: string; to: string; }>;
        "withDateFilter": boolean;
    }
    interface InsFilterItem {
        "closeFilter": () => Promise<void>;
        "getSelected": () => Promise<any>;
        "name": string;
        "options": any;
        "selected": any;
    }
    interface InsHeader {
        "hasMenuToggle": boolean;
        "supportLink": string;
        "toggleNav": () => Promise<void>;
        "toggleSidebar": () => Promise<void>;
    }
    interface InsHeaderUser {
        "app": boolean;
        "formattedRoute": string;
        "logoutLink": string;
        "name": string;
        "profileLink": string;
        "renderMyProfile": () => Promise<void>;
        "routePageHandler": () => Promise<void>;
    }
    interface InsHeading {
        "backgroundColor": string;
        "change": string;
        "editable": boolean;
        "label": string;
        "level": number;
        "maxlength": string;
        "name": string;
        "withoutLine": boolean;
    }
    interface InsImagePicker {
        "buttonColor": string;
        "fileName": any;
        "imgType": string;
        "label": string;
        "name": string;
        "notImageFile": boolean;
        "placeholder": string;
        "uploadImgContainer": string;
        "uploadImgRecFileSize": number;
        "uploadImgRecHeight": number;
        "uploadImgRecWidth": number;
        "value": any;
    }
    interface InsInfoTable {
        "emptyValue": string;
        "heading": string;
        "loaderIcon": any;
        "loaderMessage": any;
        "loaderTitle": any;
        "loadingScreen": boolean;
        "noWrap": boolean;
        "renderHtml": boolean;
        "tableData": any;
        "textOverflow": string;
    }
    interface InsInput {
        "activated": boolean;
        "disabled": boolean;
        "errorMessage": string;
        "field": string;
        "fieldId": string;
        "hasError": boolean;
        "icon": string;
        "iconEvent": boolean;
        "iconTitle": string;
        "label": string;
        "max": string;
        "maxlength": string;
        "min": string;
        "name": string;
        "placeholder": string;
        "readonly": boolean;
        "required": boolean;
        "step": string;
        "value": string;
    }
    interface InsInputFile {
        "acceptedFiles": string;
        "autoUpload": boolean;
        "buildFormData": (s3Data: any, formData: any) => Promise<void>;
        "capture": string;
        "credentialsUrl": string;
        "disabled": boolean;
        "errorMessage": string;
        "fieldName": string;
        "fieldType": string;
        "fileIcon": string;
        "getDropzoneInstance": () => Promise<any>;
        "getFilesList": () => Promise<any>;
        "getS3Credentials": () => Promise<unknown>;
        "getUploadingFiles": () => Promise<any>;
        "hasError": boolean;
        "label": string;
        "maxFileSize": number;
        "maxFileSizeLabel": string;
        "maxFiles": number;
        "maxFilesLabel": string;
        "name": string;
        "placeholder": string;
        "processS3AutoUpload": (file: any) => Promise<void>;
        "removeFiles": () => Promise<void>;
        "required": boolean;
        "s3Data": object;
        "setFiles": (files: any) => Promise<void>;
        "setS3FormData": () => Promise<void>;
        "showLimit": boolean;
        "showNotifications": boolean;
        "trigger": () => Promise<void>;
        "uploadErrorNotification": () => Promise<void>;
        "value": any;
    }
    interface InsInputMultiple {
        "disabled": boolean;
        "errorMessage": string;
        "hasError": boolean;
        "label": string;
        "name": string;
        "readonly": boolean;
        "removeDuplicates": boolean;
        "setValue": (value: any) => Promise<void>;
        "temp": string;
        "val": () => Promise<any>;
        "value": any;
    }
    interface InsInputTel {
        "areaCode": string;
        "areacodePlaceholder": string;
        "areacodeValue": string;
        "countryCode": string;
        "disabled": boolean;
        "errorMessage": string;
        "getCountryData": () => Promise<any>;
        "getValue": () => Promise<string>;
        "hasError": boolean;
        "label": string;
        "noAreacode": boolean;
        "phoneNumber": string;
        "phonenumPlaceholder": string;
        "phonenumValue": string;
        "readonly": boolean;
        "required": boolean;
        "setCountry": (country: any) => Promise<void>;
        "setCountryCode": (code: any) => Promise<void>;
    }
    interface InsLineChart {
        "categories": any;
        "chartData": any;
        "name": string;
    }
    interface InsLoader {
        "iconColor": string;
        "imageSource": string;
        "stateIcon": string;
        "stateMessage": string;
        "stateTitle": string;
        "useImage": boolean;
    }
    interface InsMarkdown {
        "label": string;
        "value": string;
    }
    interface InsMarkdownEditor {
        "errorMessage": string;
        "hasError": boolean;
        "label": string;
        "name": string;
        "readonly": boolean;
        "required": boolean;
        "val": () => Promise<any>;
        "value": string;
    }
    interface InsModal {
        "buttonAlignment": string;
        "childModal": any;
        "close": () => Promise<void>;
        "closeButtonColor": string;
        "closeButtonIcon": string;
        "closeButtonLabel": string;
        "confirmButtonColor": string;
        "confirmButtonIcon": string;
        "confirmButtonLabel": string;
        "confirmation": boolean;
        "heading": string;
        "height": string;
        "light": boolean;
        "noButton": boolean;
        "open": () => Promise<void>;
        "parentClosed": (type: any) => Promise<void>;
        "parentRender": string;
        "preventClickOutside": boolean;
        "value": any;
        "width": string;
        "withBackdrop": boolean;
    }
    interface InsPieChart {
        "chartData": Array<any>;
        "colors": Array<any>;
        "dataLabels": boolean;
        "endAngle": number;
        "fillColor": string;
        "heading": string;
        "innerSize": string;
        "innerTitle": boolean;
        "legends": boolean;
        "reRenderChart": (chartData: any) => Promise<void>;
        "size": string;
        "startAngle": number;
        "titleOffset": number;
    }
    interface InsProgressBar {
        "hidden": boolean;
        "progress": number;
        "text": string;
        "total": number;
    }
    interface InsRadio {
        "checked": boolean;
        "disabled": boolean;
        "label": any;
        "name": any;
        "staticValue": any;
        "value": any;
    }
    interface InsRenderer {
        "app": boolean;
        "label": string;
        "link": string;
        "pushHistory": (title: any, childPage?: boolean) => Promise<void>;
        "resizeIframe": () => Promise<void>;
        "route": any;
        "updateRoute": (newRoutes: any, noRedirect: boolean, iframe: any) => Promise<void>;
        "updateRouteLabel": (value: any) => Promise<void>;
    }
    interface InsSelect {
        "button": boolean;
        "buttonLabel": string;
        "closeOptions": () => Promise<void>;
        "collapseSection": () => Promise<void>;
        "disableNoResult": () => Promise<boolean>;
        "disabled": boolean;
        "dropUp": boolean;
        "dynamicPlaceholder": string;
        "dynamicSearch": boolean;
        "enableNoResult": () => Promise<boolean>;
        "errorMessage": string;
        "expandSection": () => Promise<void>;
        "getAllOptions": () => Promise<NodeListOf<HTMLInsSelectOptionElement>>;
        "hasError": boolean;
        "infiniteScroll": boolean;
        "initializing": boolean;
        "label": string;
        "multiple": boolean;
        "name": string;
        "openOptions": () => Promise<void>;
        "placeholder": string;
        "readonly": boolean;
        "searchable": boolean;
        "selected_values": any;
        "setInsSelectDefaultValue": () => Promise<void>;
        "setLoadingState": (state: any) => Promise<boolean>;
        "setSearchingState": (state: any) => Promise<boolean>;
        "setSelectedFromValue": (value?: any) => Promise<void>;
        "setValue": (value: any) => Promise<void>;
        "small": boolean;
        "toggleInsSelectOptions": () => Promise<void>;
        "value": any;
        "withDynamicOption": boolean;
    }
    interface InsSelectGroup {
        "label": string;
    }
    interface InsSelectOption {
        "activate": () => Promise<void>;
        "deactivate": () => Promise<void>;
        "default": boolean;
        "disabled": boolean;
        "hideOption": () => Promise<void>;
        "label": string;
        "showOption": () => Promise<void>;
        "value": string;
    }
    interface InsSidebar {
        "fullLogo": string;
        "iconLogo": string;
        "minimise": () => Promise<void>;
    }
    interface InsSidebarFooter {
        "toggleSidebar": () => Promise<void>;
    }
    interface InsSidebarFooterButton {
        "icon": string;
        "insSidebarFooterButtonOnClick": (event: any) => Promise<void>;
        "open": string;
    }
    interface InsSidebarFooterMenu {
        "hideMenu": () => Promise<void>;
        "icon": string;
        "label": string;
        "showMenu": () => Promise<void>;
        "toggleMenu": () => Promise<void>;
    }
    interface InsSidebarItem {
        "activate": () => Promise<void>;
        "activateParent": () => Promise<void>;
        "app": boolean;
        "deactivate": () => Promise<void>;
        "footerLink": string;
        "formatRoute": () => Promise<any>;
        "hideSubMenu": () => Promise<void>;
        "icon": any;
        "label": string;
        "landingPage": boolean;
        "link": any;
        "routePageHandler": (e: any) => Promise<{ crumbs: any[]; }>;
        "showSubMenu": () => Promise<void>;
        "withSubmenu": boolean;
    }
    interface InsSort {
        "arrange": (sortable: any) => Promise<void>;
        "cloneOnDrag": boolean;
        "disabled": boolean;
        "droppable": boolean;
        "getSortOrder": () => Promise<{}>;
        "ignoreElements": string;
        "insDraggable": boolean;
        "sort": boolean;
        "sortGroup": string;
        "wrapperClass": string;
    }
    interface InsSparkline {
        "chartData": any;
        "description": string;
        "icon": string;
        "movement": any;
        "name": string;
        "percentage": any;
        "value": string;
    }
    interface InsTab {
        "activateTab": (place: any) => Promise<void>;
        "tabs": any;
    }
    interface InsTabItem {
        "activate": () => Promise<void>;
        "active": boolean;
        "deactivate": () => Promise<void>;
        "disabled": boolean;
        "hasError": boolean;
        "icon": string;
        "label": string;
        "noPadding": boolean;
    }
    interface InsTable {
        "bulkActions": any;
        "currency": string;
        "defaultBulkAction": string;
        "emptyValue": string;
        "heading": string;
        "initialSearch": string;
        "loaderIcon": any;
        "loaderMessage": any;
        "loaderTitle": any;
        "loadingScreen": boolean;
        "noWrap": boolean;
        "pageNumber": number;
        "pageSize": number;
        "pageSizeOptions": any;
        "paginationText": string;
        "resetSelections": () => Promise<void>;
        "rowActions": any;
        "searchPosition": string;
        "searchbarPlaceholder": string;
        "selectedRows": any;
        "setBulkAction": (value: any) => Promise<void>;
        "sortKeyword": string;
        "sortOrder": boolean;
        "staticTable": boolean;
        "tableData": any;
        "tableHeaders": any;
        "textOverflow": string;
        "totalCount": any;
        "updatePageInfo": () => Promise<void>;
        "updatedRows": any;
        "withoutPagination": boolean;
        "withoutSearch": boolean;
    }
    interface InsTableRow {
    }
    interface InsTableTd {
    }
    interface InsTableTh {
    }
    interface InsTag {
        "backgroundColor": string;
        "color": string;
        "fontColor": string;
        "fontInherit": boolean;
        "icon": string;
        "label": string;
        "light": boolean;
    }
    interface InsTextarea {
        "disabled": boolean;
        "errorMessage": string;
        "hasError": boolean;
        "label": string;
        "maxlength": string;
        "name": string;
        "placeholder": string;
        "readonly": boolean;
        "required": boolean;
        "value": string;
    }
    interface InsThumbnail {
        "alt": string;
        "label": string;
        "name": string;
        "src": string;
        "thumbnail": string;
    }
    interface InsTimeline {
        "label": string;
        "loadingScreen": boolean;
        "staticTimeline": boolean;
        "timelineData": any;
    }
    interface InsTimelineItem {
        "color": string;
        "datetime": string;
        "heading": string;
        "icon": string;
        "inline": boolean;
        "solid": boolean;
    }
    interface InsTimepicker {
        "disabled": boolean;
        "errorMessage": string;
        "hasError": boolean;
        "icon": string;
        "label": string;
        "maxTime": string;
        "minTime": string;
        "name": string;
        "noMeridiem": boolean;
        "placeholder": string;
        "readonly": boolean;
        "value": string;
    }
    interface InsToggleSwitch {
        "checked": boolean;
        "disabled": boolean;
        "falseValue": string;
        "label": string;
        "name": string;
        "trueValue": string;
        "value": string;
    }
    interface InsTooltip {
        "autoWidth": boolean;
        "background": boolean;
        "closeOnClick": boolean;
        "content": string;
        "html": boolean;
        "icon": any;
        "label": string;
        "position": any;
        "shape": string;
        "trigger": string;
        "width": string;
    }
}
declare global {
    interface HTMLInsAccordionElement extends Components.InsAccordion, HTMLStencilElement {
    }
    var HTMLInsAccordionElement: {
        prototype: HTMLInsAccordionElement;
        new (): HTMLInsAccordionElement;
    };
    interface HTMLInsAccordionItemElement extends Components.InsAccordionItem, HTMLStencilElement {
    }
    var HTMLInsAccordionItemElement: {
        prototype: HTMLInsAccordionItemElement;
        new (): HTMLInsAccordionItemElement;
    };
    interface HTMLInsAccordionLinkElement extends Components.InsAccordionLink, HTMLStencilElement {
    }
    var HTMLInsAccordionLinkElement: {
        prototype: HTMLInsAccordionLinkElement;
        new (): HTMLInsAccordionLinkElement;
    };
    interface HTMLInsAdminElement extends Components.InsAdmin, HTMLStencilElement {
    }
    var HTMLInsAdminElement: {
        prototype: HTMLInsAdminElement;
        new (): HTMLInsAdminElement;
    };
    interface HTMLInsBackdropElement extends Components.InsBackdrop, HTMLStencilElement {
    }
    var HTMLInsBackdropElement: {
        prototype: HTMLInsBackdropElement;
        new (): HTMLInsBackdropElement;
    };
    interface HTMLInsBarChartElement extends Components.InsBarChart, HTMLStencilElement {
    }
    var HTMLInsBarChartElement: {
        prototype: HTMLInsBarChartElement;
        new (): HTMLInsBarChartElement;
    };
    interface HTMLInsBreadcrumbsElement extends Components.InsBreadcrumbs, HTMLStencilElement {
    }
    var HTMLInsBreadcrumbsElement: {
        prototype: HTMLInsBreadcrumbsElement;
        new (): HTMLInsBreadcrumbsElement;
    };
    interface HTMLInsButtonElement extends Components.InsButton, HTMLStencilElement {
    }
    var HTMLInsButtonElement: {
        prototype: HTMLInsButtonElement;
        new (): HTMLInsButtonElement;
    };
    interface HTMLInsButtonGroupElement extends Components.InsButtonGroup, HTMLStencilElement {
    }
    var HTMLInsButtonGroupElement: {
        prototype: HTMLInsButtonGroupElement;
        new (): HTMLInsButtonGroupElement;
    };
    interface HTMLInsCardElement extends Components.InsCard, HTMLStencilElement {
    }
    var HTMLInsCardElement: {
        prototype: HTMLInsCardElement;
        new (): HTMLInsCardElement;
    };
    interface HTMLInsCarouselElement extends Components.InsCarousel, HTMLStencilElement {
    }
    var HTMLInsCarouselElement: {
        prototype: HTMLInsCarouselElement;
        new (): HTMLInsCarouselElement;
    };
    interface HTMLInsChartElement extends Components.InsChart, HTMLStencilElement {
    }
    var HTMLInsChartElement: {
        prototype: HTMLInsChartElement;
        new (): HTMLInsChartElement;
    };
    interface HTMLInsCheckboxElement extends Components.InsCheckbox, HTMLStencilElement {
    }
    var HTMLInsCheckboxElement: {
        prototype: HTMLInsCheckboxElement;
        new (): HTMLInsCheckboxElement;
    };
    interface HTMLInsCheckboxCardElement extends Components.InsCheckboxCard, HTMLStencilElement {
    }
    var HTMLInsCheckboxCardElement: {
        prototype: HTMLInsCheckboxCardElement;
        new (): HTMLInsCheckboxCardElement;
    };
    interface HTMLInsContentElement extends Components.InsContent, HTMLStencilElement {
    }
    var HTMLInsContentElement: {
        prototype: HTMLInsContentElement;
        new (): HTMLInsContentElement;
    };
    interface HTMLInsCreditCardElement extends Components.InsCreditCard, HTMLStencilElement {
    }
    var HTMLInsCreditCardElement: {
        prototype: HTMLInsCreditCardElement;
        new (): HTMLInsCreditCardElement;
    };
    interface HTMLInsDateTimeElement extends Components.InsDateTime, HTMLStencilElement {
    }
    var HTMLInsDateTimeElement: {
        prototype: HTMLInsDateTimeElement;
        new (): HTMLInsDateTimeElement;
    };
    interface HTMLInsDatepickerElement extends Components.InsDatepicker, HTMLStencilElement {
    }
    var HTMLInsDatepickerElement: {
        prototype: HTMLInsDatepickerElement;
        new (): HTMLInsDatepickerElement;
    };
    interface HTMLInsDrawerElement extends Components.InsDrawer, HTMLStencilElement {
    }
    var HTMLInsDrawerElement: {
        prototype: HTMLInsDrawerElement;
        new (): HTMLInsDrawerElement;
    };
    interface HTMLInsFilterElement extends Components.InsFilter, HTMLStencilElement {
    }
    var HTMLInsFilterElement: {
        prototype: HTMLInsFilterElement;
        new (): HTMLInsFilterElement;
    };
    interface HTMLInsFilterItemElement extends Components.InsFilterItem, HTMLStencilElement {
    }
    var HTMLInsFilterItemElement: {
        prototype: HTMLInsFilterItemElement;
        new (): HTMLInsFilterItemElement;
    };
    interface HTMLInsHeaderElement extends Components.InsHeader, HTMLStencilElement {
    }
    var HTMLInsHeaderElement: {
        prototype: HTMLInsHeaderElement;
        new (): HTMLInsHeaderElement;
    };
    interface HTMLInsHeaderUserElement extends Components.InsHeaderUser, HTMLStencilElement {
    }
    var HTMLInsHeaderUserElement: {
        prototype: HTMLInsHeaderUserElement;
        new (): HTMLInsHeaderUserElement;
    };
    interface HTMLInsHeadingElement extends Components.InsHeading, HTMLStencilElement {
    }
    var HTMLInsHeadingElement: {
        prototype: HTMLInsHeadingElement;
        new (): HTMLInsHeadingElement;
    };
    interface HTMLInsImagePickerElement extends Components.InsImagePicker, HTMLStencilElement {
    }
    var HTMLInsImagePickerElement: {
        prototype: HTMLInsImagePickerElement;
        new (): HTMLInsImagePickerElement;
    };
    interface HTMLInsInfoTableElement extends Components.InsInfoTable, HTMLStencilElement {
    }
    var HTMLInsInfoTableElement: {
        prototype: HTMLInsInfoTableElement;
        new (): HTMLInsInfoTableElement;
    };
    interface HTMLInsInputElement extends Components.InsInput, HTMLStencilElement {
    }
    var HTMLInsInputElement: {
        prototype: HTMLInsInputElement;
        new (): HTMLInsInputElement;
    };
    interface HTMLInsInputFileElement extends Components.InsInputFile, HTMLStencilElement {
    }
    var HTMLInsInputFileElement: {
        prototype: HTMLInsInputFileElement;
        new (): HTMLInsInputFileElement;
    };
    interface HTMLInsInputMultipleElement extends Components.InsInputMultiple, HTMLStencilElement {
    }
    var HTMLInsInputMultipleElement: {
        prototype: HTMLInsInputMultipleElement;
        new (): HTMLInsInputMultipleElement;
    };
    interface HTMLInsInputTelElement extends Components.InsInputTel, HTMLStencilElement {
    }
    var HTMLInsInputTelElement: {
        prototype: HTMLInsInputTelElement;
        new (): HTMLInsInputTelElement;
    };
    interface HTMLInsLineChartElement extends Components.InsLineChart, HTMLStencilElement {
    }
    var HTMLInsLineChartElement: {
        prototype: HTMLInsLineChartElement;
        new (): HTMLInsLineChartElement;
    };
    interface HTMLInsLoaderElement extends Components.InsLoader, HTMLStencilElement {
    }
    var HTMLInsLoaderElement: {
        prototype: HTMLInsLoaderElement;
        new (): HTMLInsLoaderElement;
    };
    interface HTMLInsMarkdownElement extends Components.InsMarkdown, HTMLStencilElement {
    }
    var HTMLInsMarkdownElement: {
        prototype: HTMLInsMarkdownElement;
        new (): HTMLInsMarkdownElement;
    };
    interface HTMLInsMarkdownEditorElement extends Components.InsMarkdownEditor, HTMLStencilElement {
    }
    var HTMLInsMarkdownEditorElement: {
        prototype: HTMLInsMarkdownEditorElement;
        new (): HTMLInsMarkdownEditorElement;
    };
    interface HTMLInsModalElement extends Components.InsModal, HTMLStencilElement {
    }
    var HTMLInsModalElement: {
        prototype: HTMLInsModalElement;
        new (): HTMLInsModalElement;
    };
    interface HTMLInsPieChartElement extends Components.InsPieChart, HTMLStencilElement {
    }
    var HTMLInsPieChartElement: {
        prototype: HTMLInsPieChartElement;
        new (): HTMLInsPieChartElement;
    };
    interface HTMLInsProgressBarElement extends Components.InsProgressBar, HTMLStencilElement {
    }
    var HTMLInsProgressBarElement: {
        prototype: HTMLInsProgressBarElement;
        new (): HTMLInsProgressBarElement;
    };
    interface HTMLInsRadioElement extends Components.InsRadio, HTMLStencilElement {
    }
    var HTMLInsRadioElement: {
        prototype: HTMLInsRadioElement;
        new (): HTMLInsRadioElement;
    };
    interface HTMLInsRendererElement extends Components.InsRenderer, HTMLStencilElement {
    }
    var HTMLInsRendererElement: {
        prototype: HTMLInsRendererElement;
        new (): HTMLInsRendererElement;
    };
    interface HTMLInsSelectElement extends Components.InsSelect, HTMLStencilElement {
    }
    var HTMLInsSelectElement: {
        prototype: HTMLInsSelectElement;
        new (): HTMLInsSelectElement;
    };
    interface HTMLInsSelectGroupElement extends Components.InsSelectGroup, HTMLStencilElement {
    }
    var HTMLInsSelectGroupElement: {
        prototype: HTMLInsSelectGroupElement;
        new (): HTMLInsSelectGroupElement;
    };
    interface HTMLInsSelectOptionElement extends Components.InsSelectOption, HTMLStencilElement {
    }
    var HTMLInsSelectOptionElement: {
        prototype: HTMLInsSelectOptionElement;
        new (): HTMLInsSelectOptionElement;
    };
    interface HTMLInsSidebarElement extends Components.InsSidebar, HTMLStencilElement {
    }
    var HTMLInsSidebarElement: {
        prototype: HTMLInsSidebarElement;
        new (): HTMLInsSidebarElement;
    };
    interface HTMLInsSidebarFooterElement extends Components.InsSidebarFooter, HTMLStencilElement {
    }
    var HTMLInsSidebarFooterElement: {
        prototype: HTMLInsSidebarFooterElement;
        new (): HTMLInsSidebarFooterElement;
    };
    interface HTMLInsSidebarFooterButtonElement extends Components.InsSidebarFooterButton, HTMLStencilElement {
    }
    var HTMLInsSidebarFooterButtonElement: {
        prototype: HTMLInsSidebarFooterButtonElement;
        new (): HTMLInsSidebarFooterButtonElement;
    };
    interface HTMLInsSidebarFooterMenuElement extends Components.InsSidebarFooterMenu, HTMLStencilElement {
    }
    var HTMLInsSidebarFooterMenuElement: {
        prototype: HTMLInsSidebarFooterMenuElement;
        new (): HTMLInsSidebarFooterMenuElement;
    };
    interface HTMLInsSidebarItemElement extends Components.InsSidebarItem, HTMLStencilElement {
    }
    var HTMLInsSidebarItemElement: {
        prototype: HTMLInsSidebarItemElement;
        new (): HTMLInsSidebarItemElement;
    };
    interface HTMLInsSortElement extends Components.InsSort, HTMLStencilElement {
    }
    var HTMLInsSortElement: {
        prototype: HTMLInsSortElement;
        new (): HTMLInsSortElement;
    };
    interface HTMLInsSparklineElement extends Components.InsSparkline, HTMLStencilElement {
    }
    var HTMLInsSparklineElement: {
        prototype: HTMLInsSparklineElement;
        new (): HTMLInsSparklineElement;
    };
    interface HTMLInsTabElement extends Components.InsTab, HTMLStencilElement {
    }
    var HTMLInsTabElement: {
        prototype: HTMLInsTabElement;
        new (): HTMLInsTabElement;
    };
    interface HTMLInsTabItemElement extends Components.InsTabItem, HTMLStencilElement {
    }
    var HTMLInsTabItemElement: {
        prototype: HTMLInsTabItemElement;
        new (): HTMLInsTabItemElement;
    };
    interface HTMLInsTableElement extends Components.InsTable, HTMLStencilElement {
    }
    var HTMLInsTableElement: {
        prototype: HTMLInsTableElement;
        new (): HTMLInsTableElement;
    };
    interface HTMLInsTableRowElement extends Components.InsTableRow, HTMLStencilElement {
    }
    var HTMLInsTableRowElement: {
        prototype: HTMLInsTableRowElement;
        new (): HTMLInsTableRowElement;
    };
    interface HTMLInsTableTdElement extends Components.InsTableTd, HTMLStencilElement {
    }
    var HTMLInsTableTdElement: {
        prototype: HTMLInsTableTdElement;
        new (): HTMLInsTableTdElement;
    };
    interface HTMLInsTableThElement extends Components.InsTableTh, HTMLStencilElement {
    }
    var HTMLInsTableThElement: {
        prototype: HTMLInsTableThElement;
        new (): HTMLInsTableThElement;
    };
    interface HTMLInsTagElement extends Components.InsTag, HTMLStencilElement {
    }
    var HTMLInsTagElement: {
        prototype: HTMLInsTagElement;
        new (): HTMLInsTagElement;
    };
    interface HTMLInsTextareaElement extends Components.InsTextarea, HTMLStencilElement {
    }
    var HTMLInsTextareaElement: {
        prototype: HTMLInsTextareaElement;
        new (): HTMLInsTextareaElement;
    };
    interface HTMLInsThumbnailElement extends Components.InsThumbnail, HTMLStencilElement {
    }
    var HTMLInsThumbnailElement: {
        prototype: HTMLInsThumbnailElement;
        new (): HTMLInsThumbnailElement;
    };
    interface HTMLInsTimelineElement extends Components.InsTimeline, HTMLStencilElement {
    }
    var HTMLInsTimelineElement: {
        prototype: HTMLInsTimelineElement;
        new (): HTMLInsTimelineElement;
    };
    interface HTMLInsTimelineItemElement extends Components.InsTimelineItem, HTMLStencilElement {
    }
    var HTMLInsTimelineItemElement: {
        prototype: HTMLInsTimelineItemElement;
        new (): HTMLInsTimelineItemElement;
    };
    interface HTMLInsTimepickerElement extends Components.InsTimepicker, HTMLStencilElement {
    }
    var HTMLInsTimepickerElement: {
        prototype: HTMLInsTimepickerElement;
        new (): HTMLInsTimepickerElement;
    };
    interface HTMLInsToggleSwitchElement extends Components.InsToggleSwitch, HTMLStencilElement {
    }
    var HTMLInsToggleSwitchElement: {
        prototype: HTMLInsToggleSwitchElement;
        new (): HTMLInsToggleSwitchElement;
    };
    interface HTMLInsTooltipElement extends Components.InsTooltip, HTMLStencilElement {
    }
    var HTMLInsTooltipElement: {
        prototype: HTMLInsTooltipElement;
        new (): HTMLInsTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "ins-accordion": HTMLInsAccordionElement;
        "ins-accordion-item": HTMLInsAccordionItemElement;
        "ins-accordion-link": HTMLInsAccordionLinkElement;
        "ins-admin": HTMLInsAdminElement;
        "ins-backdrop": HTMLInsBackdropElement;
        "ins-bar-chart": HTMLInsBarChartElement;
        "ins-breadcrumbs": HTMLInsBreadcrumbsElement;
        "ins-button": HTMLInsButtonElement;
        "ins-button-group": HTMLInsButtonGroupElement;
        "ins-card": HTMLInsCardElement;
        "ins-carousel": HTMLInsCarouselElement;
        "ins-chart": HTMLInsChartElement;
        "ins-checkbox": HTMLInsCheckboxElement;
        "ins-checkbox-card": HTMLInsCheckboxCardElement;
        "ins-content": HTMLInsContentElement;
        "ins-credit-card": HTMLInsCreditCardElement;
        "ins-date-time": HTMLInsDateTimeElement;
        "ins-datepicker": HTMLInsDatepickerElement;
        "ins-drawer": HTMLInsDrawerElement;
        "ins-filter": HTMLInsFilterElement;
        "ins-filter-item": HTMLInsFilterItemElement;
        "ins-header": HTMLInsHeaderElement;
        "ins-header-user": HTMLInsHeaderUserElement;
        "ins-heading": HTMLInsHeadingElement;
        "ins-image-picker": HTMLInsImagePickerElement;
        "ins-info-table": HTMLInsInfoTableElement;
        "ins-input": HTMLInsInputElement;
        "ins-input-file": HTMLInsInputFileElement;
        "ins-input-multiple": HTMLInsInputMultipleElement;
        "ins-input-tel": HTMLInsInputTelElement;
        "ins-line-chart": HTMLInsLineChartElement;
        "ins-loader": HTMLInsLoaderElement;
        "ins-markdown": HTMLInsMarkdownElement;
        "ins-markdown-editor": HTMLInsMarkdownEditorElement;
        "ins-modal": HTMLInsModalElement;
        "ins-pie-chart": HTMLInsPieChartElement;
        "ins-progress-bar": HTMLInsProgressBarElement;
        "ins-radio": HTMLInsRadioElement;
        "ins-renderer": HTMLInsRendererElement;
        "ins-select": HTMLInsSelectElement;
        "ins-select-group": HTMLInsSelectGroupElement;
        "ins-select-option": HTMLInsSelectOptionElement;
        "ins-sidebar": HTMLInsSidebarElement;
        "ins-sidebar-footer": HTMLInsSidebarFooterElement;
        "ins-sidebar-footer-button": HTMLInsSidebarFooterButtonElement;
        "ins-sidebar-footer-menu": HTMLInsSidebarFooterMenuElement;
        "ins-sidebar-item": HTMLInsSidebarItemElement;
        "ins-sort": HTMLInsSortElement;
        "ins-sparkline": HTMLInsSparklineElement;
        "ins-tab": HTMLInsTabElement;
        "ins-tab-item": HTMLInsTabItemElement;
        "ins-table": HTMLInsTableElement;
        "ins-table-row": HTMLInsTableRowElement;
        "ins-table-td": HTMLInsTableTdElement;
        "ins-table-th": HTMLInsTableThElement;
        "ins-tag": HTMLInsTagElement;
        "ins-textarea": HTMLInsTextareaElement;
        "ins-thumbnail": HTMLInsThumbnailElement;
        "ins-timeline": HTMLInsTimelineElement;
        "ins-timeline-item": HTMLInsTimelineItemElement;
        "ins-timepicker": HTMLInsTimepickerElement;
        "ins-toggle-switch": HTMLInsToggleSwitchElement;
        "ins-tooltip": HTMLInsTooltipElement;
    }
}
declare namespace LocalJSX {
    interface InsAccordion {
        "defaultOpen"?: number;
        "menu"?: boolean;
        "onInsToggle"?: (event: CustomEvent<any>) => void;
    }
    interface InsAccordionItem {
        "active"?: boolean;
        "arrowActivated"?: boolean;
        "disabled"?: boolean;
        "heading"?: string;
        "icon"?: string;
        "link"?: string;
        "linkTarget"?: string;
    }
    interface InsAccordionLink {
        "active"?: boolean;
        "disabled"?: boolean;
        "icon"?: string;
        "label"?: string;
        "link"?: string;
        "linkTarget"?: string;
        "linkTitle"?: string;
    }
    interface InsAdmin {
    }
    interface InsBackdrop {
        "light"?: boolean;
    }
    interface InsBarChart {
        "categories"?: Array<any>;
        "chartData"?: Array<any>;
        "horizontal"?: boolean;
        "name"?: string;
        "stacked"?: boolean;
    }
    interface InsBreadcrumbs {
        "breadcrumbs"?: Array<any>;
        "onRoutePage"?: (event: CustomEvent<any>) => void;
    }
    interface InsButton {
        "color"?: string;
        "cursor"?: string;
        "data"?: string;
        "disabled"?: boolean;
        "dropdown"?: boolean;
        "icon"?: string;
        "label"?: string;
        "loading"?: boolean;
        "onInsClick"?: (event: CustomEvent<any>) => void;
        "onInsClickOption"?: (event: CustomEvent<any>) => void;
        "options"?: string;
        "outlined"?: boolean;
        "size"?: string;
        "solid"?: boolean;
        "textTransform"?: string;
        "type"?: string;
    }
    interface InsButtonGroup {
        "activeIndex"?: number;
        "activeOption"?: string;
        "color"?: string;
        "disabled"?: boolean;
        "onInsButtonAction"?: (event: CustomEvent<any>) => void;
        "options"?: string;
        "size"?: string;
    }
    interface InsCard {
        "noPadding"?: boolean;
        "outlined"?: boolean;
        "steady"?: boolean;
    }
    interface InsCarousel {
        "autoplay"?: boolean;
        "bindTo"?: string;
        "bodyText"?: string;
        "ctaColor"?: string;
        "ctaDisabled"?: boolean;
        "ctaLabel"?: string;
        "ctaLink"?: string;
        "ctaLinkTarget"?: string;
        "duration"?: number;
        "heading"?: string;
        "height"?: string;
        "layout"?: number;
        "loop"?: boolean;
        "noCarouselButton"?: boolean;
        "noPagination"?: boolean;
        "onSlide"?: (event: CustomEvent<any>) => void;
        "perPage"?: number;
        "startIndex"?: number;
        "subHeading"?: string;
        "transition"?: number;
        "width"?: string;
    }
    interface InsChart {
    }
    interface InsCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "falseValue"?: string;
        "label"?: string;
        "name"?: string;
        "onInsClick"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "trueValue"?: string;
        "value"?: string;
    }
    interface InsCheckboxCard {
        "disabled"?: boolean;
        "label"?: string;
        "name"?: string;
        "noPadding"?: boolean;
        "onInsClick"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "selected"?: boolean;
        "selectedColor"?: string;
        "tabOrder"?: string;
        "value"?: string;
    }
    interface InsContent {
    }
    interface InsCreditCard {
        "active"?: boolean;
        "brand"?: string;
        "expired"?: boolean;
        "expiryMonth"?: string;
        "expiryYear"?: string;
        "fullYear"?: boolean;
        "lastFour"?: string;
        "onInsCreditCardClicked"?: (event: CustomEvent<any>) => void;
        "onInsCreditCardClosed"?: (event: CustomEvent<any>) => void;
        "value"?: string;
    }
    interface InsDateTime {
        "disabled"?: boolean;
        "errorMessage"?: string;
        "format"?: string;
        "hasError"?: boolean;
        "icon"?: string;
        "label"?: string;
        "maxDate"?: string;
        "maxTime"?: string;
        "minDate"?: string;
        "minTime"?: string;
        "mode"?: string;
        "name"?: string;
        "noMeridiem"?: boolean;
        "onInsInput"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "value"?: string;
    }
    interface InsDatepicker {
        "disabled"?: boolean;
        "errorMessage"?: string;
        "format"?: string;
        "hasError"?: boolean;
        "icon"?: string;
        "label"?: string;
        "maxDate"?: string;
        "minDate"?: string;
        "name"?: string;
        "onInsInput"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "value"?: string;
    }
    interface InsDrawer {
        "backdropCanClose"?: boolean;
        "bordered"?: boolean;
        "customWidth"?: string;
        "icon"?: string;
        "isOpen"?: boolean;
        "label"?: string;
        "noPadding"?: boolean;
        "onInsToggle"?: (event: CustomEvent<any>) => void;
        "position"?: string;
        "showCloseButton"?: boolean;
        "showHeader"?: boolean;
        "stickyHeader"?: boolean;
    }
    interface InsFilter {
        "dateFrom"?: string;
        "dateOpt"?: any;
        "dateTitle"?: any;
        "dateTo"?: string;
        "defaultDate"?: string;
        "onInsDateFilter"?: (event: CustomEvent<any>) => void;
        "onInsFilter"?: (event: CustomEvent<any>) => void;
        "withDateFilter"?: boolean;
    }
    interface InsFilterItem {
        "name"?: string;
        "onInsSelect"?: (event: CustomEvent<any>) => void;
        "options"?: any;
        "selected"?: any;
    }
    interface InsHeader {
        "hasMenuToggle"?: boolean;
        "supportLink"?: string;
    }
    interface InsHeaderUser {
        "app"?: boolean;
        "formattedRoute"?: string;
        "logoutLink"?: string;
        "name"?: string;
        "onRoutePage"?: (event: CustomEvent<any>) => void;
        "profileLink"?: string;
    }
    interface InsHeading {
        "backgroundColor"?: string;
        "change"?: string;
        "editable"?: boolean;
        "label"?: string;
        "level"?: number;
        "maxlength"?: string;
        "name"?: string;
        "onInsChange"?: (event: CustomEvent<any>) => void;
        "withoutLine"?: boolean;
    }
    interface InsImagePicker {
        "buttonColor"?: string;
        "fileName"?: any;
        "imgType"?: string;
        "label"?: string;
        "name"?: string;
        "notImageFile"?: boolean;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "uploadImgContainer"?: string;
        "uploadImgRecFileSize"?: number;
        "uploadImgRecHeight"?: number;
        "uploadImgRecWidth"?: number;
        "value"?: any;
    }
    interface InsInfoTable {
        "emptyValue"?: string;
        "heading"?: string;
        "loaderIcon"?: any;
        "loaderMessage"?: any;
        "loaderTitle"?: any;
        "loadingScreen"?: boolean;
        "noWrap"?: boolean;
        "renderHtml"?: boolean;
        "tableData"?: any;
        "textOverflow"?: string;
    }
    interface InsInput {
        "activated"?: boolean;
        "disabled"?: boolean;
        "errorMessage"?: string;
        "field"?: string;
        "fieldId"?: string;
        "hasError"?: boolean;
        "icon"?: string;
        "iconEvent"?: boolean;
        "iconTitle"?: string;
        "label"?: string;
        "max"?: string;
        "maxlength"?: string;
        "min"?: string;
        "name"?: string;
        "onInsBlur"?: (event: CustomEvent<any>) => void;
        "onInsIconClick"?: (event: CustomEvent<any>) => void;
        "onInsInput"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "step"?: string;
        "value"?: string;
    }
    interface InsInputFile {
        "acceptedFiles"?: string;
        "autoUpload"?: boolean;
        "capture"?: string;
        "credentialsUrl"?: string;
        "disabled"?: boolean;
        "errorMessage"?: string;
        "fieldName"?: string;
        "fieldType"?: string;
        "fileIcon"?: string;
        "hasError"?: boolean;
        "label"?: string;
        "maxFileSize"?: number;
        "maxFileSizeLabel"?: string;
        "maxFiles"?: number;
        "maxFilesLabel"?: string;
        "name"?: string;
        "onFileAdded"?: (event: CustomEvent<any>) => void;
        "onFileError"?: (event: CustomEvent<any>) => void;
        "onFileRemoved"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "required"?: boolean;
        "s3Data"?: object;
        "showLimit"?: boolean;
        "showNotifications"?: boolean;
        "value"?: any;
    }
    interface InsInputMultiple {
        "disabled"?: boolean;
        "errorMessage"?: string;
        "hasError"?: boolean;
        "label"?: string;
        "name"?: string;
        "onInsChange"?: (event: CustomEvent<any>) => void;
        "onInsInput"?: (event: CustomEvent<any>) => void;
        "readonly"?: boolean;
        "removeDuplicates"?: boolean;
        "temp"?: string;
        "value"?: any;
    }
    interface InsInputTel {
        "areaCode"?: string;
        "areacodePlaceholder"?: string;
        "areacodeValue"?: string;
        "countryCode"?: string;
        "disabled"?: boolean;
        "errorMessage"?: string;
        "hasError"?: boolean;
        "label"?: string;
        "noAreacode"?: boolean;
        "onInsInput"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "phoneNumber"?: string;
        "phonenumPlaceholder"?: string;
        "phonenumValue"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
    }
    interface InsLineChart {
        "categories"?: any;
        "chartData"?: any;
        "name"?: string;
    }
    interface InsLoader {
        "iconColor"?: string;
        "imageSource"?: string;
        "stateIcon"?: string;
        "stateMessage"?: string;
        "stateTitle"?: string;
        "useImage"?: boolean;
    }
    interface InsMarkdown {
        "label"?: string;
        "value"?: string;
    }
    interface InsMarkdownEditor {
        "errorMessage"?: string;
        "hasError"?: boolean;
        "label"?: string;
        "name"?: string;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "readonly"?: boolean;
        "required"?: boolean;
        "value"?: string;
    }
    interface InsModal {
        "buttonAlignment"?: string;
        "childModal"?: any;
        "closeButtonColor"?: string;
        "closeButtonIcon"?: string;
        "closeButtonLabel"?: string;
        "confirmButtonColor"?: string;
        "confirmButtonIcon"?: string;
        "confirmButtonLabel"?: string;
        "confirmation"?: boolean;
        "heading"?: string;
        "height"?: string;
        "light"?: boolean;
        "noButton"?: boolean;
        "onInsClose"?: (event: CustomEvent<any>) => void;
        "parentRender"?: string;
        "preventClickOutside"?: boolean;
        "value"?: any;
        "width"?: string;
        "withBackdrop"?: boolean;
    }
    interface InsPieChart {
        "chartData"?: Array<any>;
        "colors"?: Array<any>;
        "dataLabels"?: boolean;
        "endAngle"?: number;
        "fillColor"?: string;
        "heading"?: string;
        "innerSize"?: string;
        "innerTitle"?: boolean;
        "legends"?: boolean;
        "size"?: string;
        "startAngle"?: number;
        "titleOffset"?: number;
    }
    interface InsProgressBar {
        "hidden"?: boolean;
        "progress"?: number;
        "text"?: string;
        "total"?: number;
    }
    interface InsRadio {
        "checked"?: boolean;
        "disabled"?: boolean;
        "label"?: any;
        "name"?: any;
        "onInsSelect"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "staticValue"?: any;
        "value"?: any;
    }
    interface InsRenderer {
        "app"?: boolean;
        "label"?: string;
        "link"?: string;
        "route"?: any;
    }
    interface InsSelect {
        "button"?: boolean;
        "buttonLabel"?: string;
        "disabled"?: boolean;
        "dropUp"?: boolean;
        "dynamicPlaceholder"?: string;
        "dynamicSearch"?: boolean;
        "errorMessage"?: string;
        "hasError"?: boolean;
        "infiniteScroll"?: boolean;
        "initializing"?: boolean;
        "label"?: string;
        "multiple"?: boolean;
        "name"?: string;
        "onInsChange"?: (event: CustomEvent<any>) => void;
        "onInsLoadMore"?: (event: CustomEvent<any>) => void;
        "onInsSearch"?: (event: CustomEvent<any>) => void;
        "onInsSubmit"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "searchable"?: boolean;
        "selected_values"?: any;
        "small"?: boolean;
        "value"?: any;
        "withDynamicOption"?: boolean;
    }
    interface InsSelectGroup {
        "label"?: string;
    }
    interface InsSelectOption {
        "default"?: boolean;
        "disabled"?: boolean;
        "label"?: string;
        "onDefaultEvent"?: (event: CustomEvent<any>) => void;
        "onInsSelectOptionClicked"?: (event: CustomEvent<any>) => void;
        "value"?: string;
    }
    interface InsSidebar {
        "fullLogo"?: string;
        "iconLogo"?: string;
        "onInsSidebarAction"?: (event: CustomEvent<any>) => void;
    }
    interface InsSidebarFooter {
    }
    interface InsSidebarFooterButton {
        "icon"?: string;
        "onInsSidebarFooterButtonEvent"?: (event: CustomEvent<any>) => void;
        "open"?: string;
    }
    interface InsSidebarFooterMenu {
        "icon"?: string;
        "label"?: string;
    }
    interface InsSidebarItem {
        "app"?: boolean;
        "footerLink"?: string;
        "icon"?: any;
        "label"?: string;
        "landingPage"?: boolean;
        "link"?: any;
        "onRoutePage"?: (event: CustomEvent<any>) => void;
        "withSubmenu"?: boolean;
    }
    interface InsSort {
        "cloneOnDrag"?: boolean;
        "disabled"?: boolean;
        "droppable"?: boolean;
        "ignoreElements"?: string;
        "insDraggable"?: boolean;
        "onInsAdd"?: (event: CustomEvent<Object>) => void;
        "onInsChoose"?: (event: CustomEvent<Object>) => void;
        "onInsClone"?: (event: CustomEvent<Object>) => void;
        "onInsDragEnd"?: (event: CustomEvent<Object>) => void;
        "onInsDragStart"?: (event: CustomEvent<Object>) => void;
        "onInsDrop"?: (event: CustomEvent<Object>) => void;
        "onInsMove"?: (event: CustomEvent<Object>) => void;
        "onInsPositionChanged"?: (event: CustomEvent<Object>) => void;
        "onInsRemove"?: (event: CustomEvent<Object>) => void;
        "onInsUpdate"?: (event: CustomEvent<Object>) => void;
        "sort"?: boolean;
        "sortGroup"?: string;
        "wrapperClass"?: string;
    }
    interface InsSparkline {
        "chartData"?: any;
        "description"?: string;
        "icon"?: string;
        "movement"?: any;
        "name"?: string;
        "percentage"?: any;
        "value"?: string;
    }
    interface InsTab {
        "onOnchangeTab"?: (event: CustomEvent<any>) => void;
        "tabs"?: any;
    }
    interface InsTabItem {
        "active"?: boolean;
        "disabled"?: boolean;
        "hasError"?: boolean;
        "icon"?: string;
        "label"?: string;
        "noPadding"?: boolean;
        "onTabItemDisableToggled"?: (event: CustomEvent<any>) => void;
        "onTabItemError"?: (event: CustomEvent<any>) => void;
    }
    interface InsTable {
        "bulkActions"?: any;
        "currency"?: string;
        "defaultBulkAction"?: string;
        "emptyValue"?: string;
        "heading"?: string;
        "initialSearch"?: string;
        "loaderIcon"?: any;
        "loaderMessage"?: any;
        "loaderTitle"?: any;
        "loadingScreen"?: boolean;
        "noWrap"?: boolean;
        "onInsFieldChange"?: (event: CustomEvent<any>) => void;
        "onInsPaginationChange"?: (event: CustomEvent<any>) => void;
        "onInsTableBulkAction"?: (event: CustomEvent<any>) => void;
        "onInsTableRowAction"?: (event: CustomEvent<any>) => void;
        "onInsTableSearch"?: (event: CustomEvent<any>) => void;
        "onInsTableSort"?: (event: CustomEvent<any>) => void;
        "pageNumber"?: number;
        "pageSize"?: number;
        "pageSizeOptions"?: any;
        "paginationText"?: string;
        "rowActions"?: any;
        "searchPosition"?: string;
        "searchbarPlaceholder"?: string;
        "selectedRows"?: any;
        "sortKeyword"?: string;
        "sortOrder"?: boolean;
        "staticTable"?: boolean;
        "tableData"?: any;
        "tableHeaders"?: any;
        "textOverflow"?: string;
        "totalCount"?: any;
        "updatedRows"?: any;
        "withoutPagination"?: boolean;
        "withoutSearch"?: boolean;
    }
    interface InsTableRow {
    }
    interface InsTableTd {
    }
    interface InsTableTh {
    }
    interface InsTag {
        "backgroundColor"?: string;
        "color"?: string;
        "fontColor"?: string;
        "fontInherit"?: boolean;
        "icon"?: string;
        "label"?: string;
        "light"?: boolean;
    }
    interface InsTextarea {
        "disabled"?: boolean;
        "errorMessage"?: string;
        "hasError"?: boolean;
        "label"?: string;
        "maxlength"?: string;
        "name"?: string;
        "onOninput"?: (event: CustomEvent<any>) => void;
        "onValueChange"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "value"?: string;
    }
    interface InsThumbnail {
        "alt"?: string;
        "label"?: string;
        "name"?: string;
        "src"?: string;
        "thumbnail"?: string;
    }
    interface InsTimeline {
        "label"?: string;
        "loadingScreen"?: boolean;
        "staticTimeline"?: boolean;
        "timelineData"?: any;
    }
    interface InsTimelineItem {
        "color"?: string;
        "datetime"?: string;
        "heading"?: string;
        "icon"?: string;
        "inline"?: boolean;
        "solid"?: boolean;
    }
    interface InsTimepicker {
        "disabled"?: boolean;
        "errorMessage"?: string;
        "hasError"?: boolean;
        "icon"?: string;
        "label"?: string;
        "maxTime"?: string;
        "minTime"?: string;
        "name"?: string;
        "noMeridiem"?: boolean;
        "onInsInput"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "value"?: string;
    }
    interface InsToggleSwitch {
        "checked"?: boolean;
        "disabled"?: boolean;
        "falseValue"?: string;
        "label"?: string;
        "name"?: string;
        "onInsToggle"?: (event: CustomEvent<any>) => void;
        "onInsValueChange"?: (event: CustomEvent<any>) => void;
        "trueValue"?: string;
        "value"?: string;
    }
    interface InsTooltip {
        "autoWidth"?: boolean;
        "background"?: boolean;
        "closeOnClick"?: boolean;
        "content"?: string;
        "html"?: boolean;
        "icon"?: any;
        "label"?: string;
        "position"?: any;
        "shape"?: string;
        "trigger"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "ins-accordion": InsAccordion;
        "ins-accordion-item": InsAccordionItem;
        "ins-accordion-link": InsAccordionLink;
        "ins-admin": InsAdmin;
        "ins-backdrop": InsBackdrop;
        "ins-bar-chart": InsBarChart;
        "ins-breadcrumbs": InsBreadcrumbs;
        "ins-button": InsButton;
        "ins-button-group": InsButtonGroup;
        "ins-card": InsCard;
        "ins-carousel": InsCarousel;
        "ins-chart": InsChart;
        "ins-checkbox": InsCheckbox;
        "ins-checkbox-card": InsCheckboxCard;
        "ins-content": InsContent;
        "ins-credit-card": InsCreditCard;
        "ins-date-time": InsDateTime;
        "ins-datepicker": InsDatepicker;
        "ins-drawer": InsDrawer;
        "ins-filter": InsFilter;
        "ins-filter-item": InsFilterItem;
        "ins-header": InsHeader;
        "ins-header-user": InsHeaderUser;
        "ins-heading": InsHeading;
        "ins-image-picker": InsImagePicker;
        "ins-info-table": InsInfoTable;
        "ins-input": InsInput;
        "ins-input-file": InsInputFile;
        "ins-input-multiple": InsInputMultiple;
        "ins-input-tel": InsInputTel;
        "ins-line-chart": InsLineChart;
        "ins-loader": InsLoader;
        "ins-markdown": InsMarkdown;
        "ins-markdown-editor": InsMarkdownEditor;
        "ins-modal": InsModal;
        "ins-pie-chart": InsPieChart;
        "ins-progress-bar": InsProgressBar;
        "ins-radio": InsRadio;
        "ins-renderer": InsRenderer;
        "ins-select": InsSelect;
        "ins-select-group": InsSelectGroup;
        "ins-select-option": InsSelectOption;
        "ins-sidebar": InsSidebar;
        "ins-sidebar-footer": InsSidebarFooter;
        "ins-sidebar-footer-button": InsSidebarFooterButton;
        "ins-sidebar-footer-menu": InsSidebarFooterMenu;
        "ins-sidebar-item": InsSidebarItem;
        "ins-sort": InsSort;
        "ins-sparkline": InsSparkline;
        "ins-tab": InsTab;
        "ins-tab-item": InsTabItem;
        "ins-table": InsTable;
        "ins-table-row": InsTableRow;
        "ins-table-td": InsTableTd;
        "ins-table-th": InsTableTh;
        "ins-tag": InsTag;
        "ins-textarea": InsTextarea;
        "ins-thumbnail": InsThumbnail;
        "ins-timeline": InsTimeline;
        "ins-timeline-item": InsTimelineItem;
        "ins-timepicker": InsTimepicker;
        "ins-toggle-switch": InsToggleSwitch;
        "ins-tooltip": InsTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ins-accordion": LocalJSX.InsAccordion & JSXBase.HTMLAttributes<HTMLInsAccordionElement>;
            "ins-accordion-item": LocalJSX.InsAccordionItem & JSXBase.HTMLAttributes<HTMLInsAccordionItemElement>;
            "ins-accordion-link": LocalJSX.InsAccordionLink & JSXBase.HTMLAttributes<HTMLInsAccordionLinkElement>;
            "ins-admin": LocalJSX.InsAdmin & JSXBase.HTMLAttributes<HTMLInsAdminElement>;
            "ins-backdrop": LocalJSX.InsBackdrop & JSXBase.HTMLAttributes<HTMLInsBackdropElement>;
            "ins-bar-chart": LocalJSX.InsBarChart & JSXBase.HTMLAttributes<HTMLInsBarChartElement>;
            "ins-breadcrumbs": LocalJSX.InsBreadcrumbs & JSXBase.HTMLAttributes<HTMLInsBreadcrumbsElement>;
            "ins-button": LocalJSX.InsButton & JSXBase.HTMLAttributes<HTMLInsButtonElement>;
            "ins-button-group": LocalJSX.InsButtonGroup & JSXBase.HTMLAttributes<HTMLInsButtonGroupElement>;
            "ins-card": LocalJSX.InsCard & JSXBase.HTMLAttributes<HTMLInsCardElement>;
            "ins-carousel": LocalJSX.InsCarousel & JSXBase.HTMLAttributes<HTMLInsCarouselElement>;
            "ins-chart": LocalJSX.InsChart & JSXBase.HTMLAttributes<HTMLInsChartElement>;
            "ins-checkbox": LocalJSX.InsCheckbox & JSXBase.HTMLAttributes<HTMLInsCheckboxElement>;
            "ins-checkbox-card": LocalJSX.InsCheckboxCard & JSXBase.HTMLAttributes<HTMLInsCheckboxCardElement>;
            "ins-content": LocalJSX.InsContent & JSXBase.HTMLAttributes<HTMLInsContentElement>;
            "ins-credit-card": LocalJSX.InsCreditCard & JSXBase.HTMLAttributes<HTMLInsCreditCardElement>;
            "ins-date-time": LocalJSX.InsDateTime & JSXBase.HTMLAttributes<HTMLInsDateTimeElement>;
            "ins-datepicker": LocalJSX.InsDatepicker & JSXBase.HTMLAttributes<HTMLInsDatepickerElement>;
            "ins-drawer": LocalJSX.InsDrawer & JSXBase.HTMLAttributes<HTMLInsDrawerElement>;
            "ins-filter": LocalJSX.InsFilter & JSXBase.HTMLAttributes<HTMLInsFilterElement>;
            "ins-filter-item": LocalJSX.InsFilterItem & JSXBase.HTMLAttributes<HTMLInsFilterItemElement>;
            "ins-header": LocalJSX.InsHeader & JSXBase.HTMLAttributes<HTMLInsHeaderElement>;
            "ins-header-user": LocalJSX.InsHeaderUser & JSXBase.HTMLAttributes<HTMLInsHeaderUserElement>;
            "ins-heading": LocalJSX.InsHeading & JSXBase.HTMLAttributes<HTMLInsHeadingElement>;
            "ins-image-picker": LocalJSX.InsImagePicker & JSXBase.HTMLAttributes<HTMLInsImagePickerElement>;
            "ins-info-table": LocalJSX.InsInfoTable & JSXBase.HTMLAttributes<HTMLInsInfoTableElement>;
            "ins-input": LocalJSX.InsInput & JSXBase.HTMLAttributes<HTMLInsInputElement>;
            "ins-input-file": LocalJSX.InsInputFile & JSXBase.HTMLAttributes<HTMLInsInputFileElement>;
            "ins-input-multiple": LocalJSX.InsInputMultiple & JSXBase.HTMLAttributes<HTMLInsInputMultipleElement>;
            "ins-input-tel": LocalJSX.InsInputTel & JSXBase.HTMLAttributes<HTMLInsInputTelElement>;
            "ins-line-chart": LocalJSX.InsLineChart & JSXBase.HTMLAttributes<HTMLInsLineChartElement>;
            "ins-loader": LocalJSX.InsLoader & JSXBase.HTMLAttributes<HTMLInsLoaderElement>;
            "ins-markdown": LocalJSX.InsMarkdown & JSXBase.HTMLAttributes<HTMLInsMarkdownElement>;
            "ins-markdown-editor": LocalJSX.InsMarkdownEditor & JSXBase.HTMLAttributes<HTMLInsMarkdownEditorElement>;
            "ins-modal": LocalJSX.InsModal & JSXBase.HTMLAttributes<HTMLInsModalElement>;
            "ins-pie-chart": LocalJSX.InsPieChart & JSXBase.HTMLAttributes<HTMLInsPieChartElement>;
            "ins-progress-bar": LocalJSX.InsProgressBar & JSXBase.HTMLAttributes<HTMLInsProgressBarElement>;
            "ins-radio": LocalJSX.InsRadio & JSXBase.HTMLAttributes<HTMLInsRadioElement>;
            "ins-renderer": LocalJSX.InsRenderer & JSXBase.HTMLAttributes<HTMLInsRendererElement>;
            "ins-select": LocalJSX.InsSelect & JSXBase.HTMLAttributes<HTMLInsSelectElement>;
            "ins-select-group": LocalJSX.InsSelectGroup & JSXBase.HTMLAttributes<HTMLInsSelectGroupElement>;
            "ins-select-option": LocalJSX.InsSelectOption & JSXBase.HTMLAttributes<HTMLInsSelectOptionElement>;
            "ins-sidebar": LocalJSX.InsSidebar & JSXBase.HTMLAttributes<HTMLInsSidebarElement>;
            "ins-sidebar-footer": LocalJSX.InsSidebarFooter & JSXBase.HTMLAttributes<HTMLInsSidebarFooterElement>;
            "ins-sidebar-footer-button": LocalJSX.InsSidebarFooterButton & JSXBase.HTMLAttributes<HTMLInsSidebarFooterButtonElement>;
            "ins-sidebar-footer-menu": LocalJSX.InsSidebarFooterMenu & JSXBase.HTMLAttributes<HTMLInsSidebarFooterMenuElement>;
            "ins-sidebar-item": LocalJSX.InsSidebarItem & JSXBase.HTMLAttributes<HTMLInsSidebarItemElement>;
            "ins-sort": LocalJSX.InsSort & JSXBase.HTMLAttributes<HTMLInsSortElement>;
            "ins-sparkline": LocalJSX.InsSparkline & JSXBase.HTMLAttributes<HTMLInsSparklineElement>;
            "ins-tab": LocalJSX.InsTab & JSXBase.HTMLAttributes<HTMLInsTabElement>;
            "ins-tab-item": LocalJSX.InsTabItem & JSXBase.HTMLAttributes<HTMLInsTabItemElement>;
            "ins-table": LocalJSX.InsTable & JSXBase.HTMLAttributes<HTMLInsTableElement>;
            "ins-table-row": LocalJSX.InsTableRow & JSXBase.HTMLAttributes<HTMLInsTableRowElement>;
            "ins-table-td": LocalJSX.InsTableTd & JSXBase.HTMLAttributes<HTMLInsTableTdElement>;
            "ins-table-th": LocalJSX.InsTableTh & JSXBase.HTMLAttributes<HTMLInsTableThElement>;
            "ins-tag": LocalJSX.InsTag & JSXBase.HTMLAttributes<HTMLInsTagElement>;
            "ins-textarea": LocalJSX.InsTextarea & JSXBase.HTMLAttributes<HTMLInsTextareaElement>;
            "ins-thumbnail": LocalJSX.InsThumbnail & JSXBase.HTMLAttributes<HTMLInsThumbnailElement>;
            "ins-timeline": LocalJSX.InsTimeline & JSXBase.HTMLAttributes<HTMLInsTimelineElement>;
            "ins-timeline-item": LocalJSX.InsTimelineItem & JSXBase.HTMLAttributes<HTMLInsTimelineItemElement>;
            "ins-timepicker": LocalJSX.InsTimepicker & JSXBase.HTMLAttributes<HTMLInsTimepickerElement>;
            "ins-toggle-switch": LocalJSX.InsToggleSwitch & JSXBase.HTMLAttributes<HTMLInsToggleSwitchElement>;
            "ins-tooltip": LocalJSX.InsTooltip & JSXBase.HTMLAttributes<HTMLInsTooltipElement>;
        }
    }
}
