/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface InsAccordion {
    'defaultOpen': number;
    'initAccordion': () => Promise<void>;
    'menu': boolean;
  }
  interface InsAccordionItem {
    'active': boolean;
    'arrowActivated': boolean;
    'disabled': boolean;
    'heading': string;
    'icon': string;
    'link': string;
    'linkTarget': string;
  }
  interface InsAccordionLink {
    'active': boolean;
    'disabled': boolean;
    'icon': string;
    'label': string;
    'link': string;
    'linkTarget': string;
    'linkTitle': string;
  }
  interface InsAdmin {}
  interface InsBackdrop {
    'light': boolean;
  }
  interface InsBarChart {
    'categories': Array<any>;
    'chartData': Array<any>;
    'dataSrc': string;
    'horizontal': boolean;
    'name': string;
    'reRenderChart': (chartData: any, categories: any) => Promise<void>;
    'stacked': boolean;
  }
  interface InsBaseTable {
    'bulkActions': any;
    'currency': string;
    'defaultBulkAction': string;
    'emptyValue': string;
    'heading': string;
    'initialSearch': string;
    'loaderIcon': any;
    'loaderMessage': any;
    'loaderTitle': any;
    'loadingScreen': boolean;
    'noWrap': boolean;
    'pageNumber': number;
    'pageSize': number;
    'pageSizeOptions': any;
    'paginationText': string;
    'resetSelections': () => Promise<void>;
    'rowActions': any;
    'searchPosition': string;
    'searchbarPlaceholder': string;
    'selectedRows': any;
    'setBulkAction': (value: any) => Promise<void>;
    'sortKeyword': string;
    'sortOrder': boolean;
    'staticTable': boolean;
    'tableData': any;
    'tableHeaders': any;
    'textOverflow': string;
    'totalCount': any;
    'updatePageInfo': () => Promise<void>;
    'updatedRows': any;
    'val': (attr: any, value: any) => any;
    'withoutPagination': boolean;
    'withoutSearch': boolean;
  }
  interface InsBaseTableRow {}
  interface InsBaseTableTd {}
  interface InsBaseTableTh {}
  interface InsBreadcrumbs {
    'updateCrumbs': (crumbs: any, noRedirect?: boolean) => Promise<void>;
  }
  interface InsButton {
    'color': string;
    'cursor': string;
    'data': string;
    'disabled': boolean;
    'dropdown': boolean;
    'icon': string;
    'label': string;
    'loading': boolean;
    'options': string;
    'outlined': boolean;
    'size': string;
    'solid': boolean;
    'textTransform': string;
    'type': string;
  }
  interface InsButtonGroup {
    'activeIndex': number;
    'activeOption': string;
    'color': string;
    'disabled': boolean;
    'getActiveOption': () => Promise<{ index: number; label: any; }>;
    'options': string;
    'setActiveOption': (option: any) => Promise<void>;
    'size': string;
  }
  interface InsCard {
    'noPadding': boolean;
    'outlined': boolean;
    'steady': boolean;
  }
  interface InsCarousel {
    'autoplay': boolean;
    'bindTo': string;
    'bodyText': string;
    'ctaColor': string;
    'ctaDisabled': boolean;
    'ctaLabel': string;
    'ctaLink': string;
    'ctaLinkTarget': string;
    'duration': number;
    'goTo': (slide: any) => Promise<void>;
    'heading': string;
    'height': string;
    'layout': number;
    'loop': boolean;
    'noCarouselButton': boolean;
    'noPagination': boolean;
    'perPage': number;
    'startIndex': number;
    'subHeading': string;
    'transition': number;
    'width': string;
  }
  interface InsCheckbox {
    'checked': boolean;
    'disabled': boolean;
    'falseValue': string;
    'label': string;
    'name': string;
    'trueValue': string;
    'updateCheckState': (state: any) => Promise<void>;
    'value': string;
  }
  interface InsCheckboxCard {
    'disabled': boolean;
    'label': string;
    'name': string;
    'noPadding': boolean;
    'selected': boolean;
    'selectedColor': string;
    'tabOrder': string;
    'value': string;
  }
  interface InsCodeEditor {
    'beautify': () => Promise<void>;
    'disableLineNumbers': boolean;
    'errorMessage': string;
    'hasError': boolean;
    'label': string;
    'mode': string;
    'name': string;
    'readonly': boolean;
    'refresh': () => Promise<void>;
    'theme': string;
    'val': () => any;
    'value': string;
  }
  interface InsContent {}
  interface InsCreditCard {
    'active': boolean;
    'brand': string;
    'expired': boolean;
    'expiryMonth': string;
    'expiryYear': string;
    'fullYear': boolean;
    'lastFour': string;
    'value': string;
  }
  interface InsDateTime {
    'disabled': boolean;
    'errorMessage': string;
    'format': string;
    'hasError': boolean;
    'icon': string;
    'label': string;
    'maxDate': string;
    'minDate': string;
    'name': string;
    'noMeridiem': boolean;
    'placeholder': string;
    'readonly': boolean;
    'value': string;
  }
  interface InsDatepicker {
    'disabled': boolean;
    'errorMessage': string;
    'format': string;
    'hasError': boolean;
    'icon': string;
    'label': string;
    'maxDate': string;
    'minDate': string;
    'name': string;
    'placeholder': string;
    'readonly': boolean;
    'value': string;
  }
  interface InsDrawer {
    'backdropCanClose': boolean;
    'bordered': boolean;
    'customWidth': string;
    'icon': string;
    'isOpen': boolean;
    'label': string;
    'noPadding': boolean;
    'position': string;
    'setDrawerState': (status: any) => Promise<void>;
    'showCloseButton': boolean;
    'showHeader': boolean;
    'stickyHeader': boolean;
  }
  interface InsDuration {
    'label': string;
    'name': string;
  }
  interface InsEditor {
    'classId': string;
    'disableLineNumbers': boolean;
    'errorMessage': string;
    'hasCodeEditor': boolean;
    'hasError': boolean;
    'imageUpload': boolean;
    'images': string;
    'label': string;
    'mode': string;
    'name': string;
    'pluginsList': any;
    'readonly': boolean;
    'showSource': boolean;
    'theme': string;
    'val': () => any;
    'value': string;
  }
  interface InsFavIcon {
    'buttonColor': string;
    'type': string;
  }
  interface InsFilter {
    'closeDateFilter': () => Promise<void>;
    'dateFrom': string;
    'dateOpt': any;
    'dateTitle': any;
    'dateTo': string;
    'defaultDate': string;
    'getDate': () => Promise<"All" | { from: string; to: string; }>;
    'withDateFilter': boolean;
  }
  interface InsFilterItem {
    'closeFilter': () => Promise<void>;
    'getSelected': () => any;
    'name': string;
    'options': any;
    'selected': any;
    'val': (attr: any, value: any) => any;
  }
  interface InsHeader {
    'hasMenuToggle': boolean;
    'supportLink': string;
    'toggleNav': () => Promise<void>;
    'toggleSidebar': () => Promise<void>;
  }
  interface InsHeaderUser {
    'app': boolean;
    'formattedRoute': string;
    'logoutLink': string;
    'name': string;
    'profileLink': string;
    'renderMyProfile': () => Promise<void>;
    'routePageHandler': () => Promise<void>;
    'val': (attr: any, value: any) => any;
  }
  interface InsHeading {
    'backgroundColor': string;
    'editable': boolean;
    'label': string;
    'level': number;
    'maxlength': string;
    'name': string;
    'withoutLine': boolean;
  }
  interface InsImagePicker {
    'buttonColor': string;
    'fileName': any;
    'imgType': string;
    'label': string;
    'name': string;
    'notImageFile': boolean;
    'placeholder': string;
    'uploadImgContainer': string;
    'uploadImgRecFileSize': number;
    'uploadImgRecHeight': number;
    'uploadImgRecWidth': number;
    'value': any;
  }
  interface InsInfoTable {
    'emptyValue': string;
    'heading': string;
    'loaderIcon': any;
    'loaderMessage': any;
    'loaderTitle': any;
    'loadingScreen': boolean;
    'noWrap': boolean;
    'renderHtml': boolean;
    'tableData': any;
    'textOverflow': string;
  }
  interface InsInput {
    'activated': boolean;
    'disabled': boolean;
    'errorMessage': string;
    'field': string;
    'fieldId': string;
    'hasError': boolean;
    'icon': string;
    'label': string;
    'max': string;
    'maxlength': string;
    'min': string;
    'name': string;
    'placeholder': string;
    'readonly': boolean;
    'required': boolean;
    'step': string;
    'val': (attr: any, value: any) => any;
    'value': string;
  }
  interface InsInputFile {
    'acceptedFiles': string;
    'disabled': boolean;
    'errorMessage': string;
    'fileIcon': string;
    'getFilesList': () => any;
    'hasError': boolean;
    'label': string;
    'maxFileSize': number;
    'maxFileSizeLabel': string;
    'maxFiles': number;
    'maxFilesLabel': string;
    'name': string;
    'placeholder': string;
    'removeFiles': () => Promise<void>;
    'required': boolean;
    'setFiles': (files: any) => Promise<void>;
    'showLimit': boolean;
    'value': any;
  }
  interface InsInputTel {
    'areaCode': string;
    'areacodePlaceholder': string;
    'areacodeValue': string;
    'countryCode': string;
    'disabled': boolean;
    'errorMessage': string;
    'getCountryData': () => any;
    'getValue': () => string;
    'hasError': boolean;
    'label': string;
    'noAreacode': boolean;
    'phoneNumber': string;
    'phonenumPlaceholder': string;
    'phonenumValue': string;
    'readonly': boolean;
    'required': boolean;
    'setCountry': (country: any) => Promise<void>;
    'setCountryCode': (code: any) => Promise<void>;
    'val': (attr: any, value: any) => any;
  }
  interface InsInstances {
    'instance': string;
    'instanceLink': string;
    'logoLink': string;
    'newTab': boolean;
    'val': (attr: any, value: any) => any;
  }
  interface InsInstancesItem {
    'instance': string;
    'instanceLink': string;
    'logoLink': string;
    'val': (attr: any, value: any) => any;
    'withSubItem': boolean;
  }
  interface InsInstancesSubItem {
    'instance': string;
    'link': string;
    'val': (attr: any, value: any) => any;
  }
  interface InsLineChart {
    'categories': any;
    'chartData': any;
    'dataSrc': string;
    'name': string;
    'reRenderChart': (chartData: any, categories: any) => Promise<void>;
    'val': (attr: any, value: any) => any;
  }
  interface InsLoader {
    'iconColor': string;
    'imageSource': string;
    'stateIcon': string;
    'stateMessage': string;
    'stateTitle': string;
    'useImage': boolean;
    'val': (attr: any, value: any) => any;
  }
  interface InsLogo {
    'buttonColor': string;
    'type': string;
  }
  interface InsMarkdown {
    'label': string;
    'value': string;
  }
  interface InsMarkdownEditor {
    'errorMessage': string;
    'hasError': boolean;
    'label': string;
    'name': string;
    'readonly': boolean;
    'required': boolean;
    'val': () => any;
    'value': string;
  }
  interface InsModal {
    'buttonAlignment': string;
    'childModal': any;
    'close': () => Promise<void>;
    'closeButtonColor': string;
    'closeButtonIcon': string;
    'closeButtonLabel': string;
    'confirmButtonColor': string;
    'confirmButtonIcon': string;
    'confirmButtonLabel': string;
    'confirmation': boolean;
    'heading': string;
    'height': string;
    'light': boolean;
    'noButton': boolean;
    'open': () => Promise<void>;
    'parentClosed': (type: any) => Promise<void>;
    'parentRender': string;
    'preventClickOutside': boolean;
    'value': any;
    'width': string;
    'withBackdrop': boolean;
  }
  interface InsNotifications {
    'toggleNotificationshandler': () => Promise<void>;
  }
  interface InsNotificationsItem {
    'desc': string;
    'duration': string;
    'eventType': string;
    'heading': string;
    'icon': string;
    'link': string;
    'linkLabel': string;
    'status': string;
    'val': (attr: any, value: any) => any;
  }
  interface InsPieChart {
    'chartData': Array<any>;
    'colors': Array<any>;
    'dataLabels': boolean;
    'endAngle': number;
    'fillColor': string;
    'innerSize': string;
    'innerTitle': boolean;
    'legends': boolean;
    'reRenderChart': (chartData: any) => Promise<void>;
    'size': string;
    'startAngle': number;
    'title': string;
    'titleOffset': number;
  }
  interface InsProgressBar {
    'hidden': boolean;
    'progress': number;
    'text': string;
    'total': number;
  }
  interface InsRadio {
    'checked': boolean;
    'disabled': boolean;
    'label': any;
    'name': any;
    'staticValue': any;
    'value': any;
  }
  interface InsRenderer {
    'app': boolean;
    'label': string;
    'link': string;
    'resizeIframe': () => Promise<void>;
    'route': any;
    'updateRoute': (newRoutes: any, noRedirect?: boolean) => Promise<void>;
    'updateRouteLabel': (value: any) => Promise<void>;
  }
  interface InsSearchbar {
    'isSearching': boolean;
    'name': string;
    'placeholder': string;
    'val': (attr: any, value: any) => any;
    'value': string;
  }
  interface InsSelect {
    'button': boolean;
    'buttonLabel': string;
    'collapseSection': () => Promise<void>;
    'disableNoResult': () => Promise<void>;
    'disabled': boolean;
    'dropUp': boolean;
    'dynamicPlaceholder': string;
    'dynamicSearch': boolean;
    'enableNoResult': () => Promise<void>;
    'errorMessage': string;
    'expandSection': () => Promise<void>;
    'getAllOptions': () => NodeListOf<HTMLInsSelectOptionElement>;
    'hasError': boolean;
    'infiniteScroll': boolean;
    'initializing': boolean;
    'label': string;
    'multiple': boolean;
    'name': string;
    'placeholder': string;
    'readonly': boolean;
    'searchable': boolean;
    'selected_values': any;
    'setInsSelectDefaultValue': () => Promise<void>;
    'setLoadingState': (state: any) => Promise<void>;
    'setSearchingState': (state: any) => Promise<void>;
    'setSelectedFromValue': (value?: any) => Promise<void>;
    'setValue': (value: any) => Promise<void>;
    'small': boolean;
    'toggleInsSelectOptions': () => Promise<void>;
    'value': any;
    'withDynamicOption': boolean;
  }
  interface InsSelectGroup {
    'label': string;
  }
  interface InsSelectOption {
    'activate': () => Promise<void>;
    'deactivate': () => Promise<void>;
    'default': boolean;
    'disabled': boolean;
    'hideOption': () => Promise<void>;
    'label': string;
    'showOption': () => Promise<void>;
    'val': (attr: any, value: any) => any;
    'value': string;
  }
  interface InsSidebar {
    'fullLogo': string;
    'iconLogo': string;
    'minimise': () => Promise<void>;
    'val': (attr: any, value: any) => any;
  }
  interface InsSidebarFooter {}
  interface InsSidebarFooterButton {
    'icon': string;
    'insSidebarFooterButtonOnClick': (event: any) => Promise<void>;
    'open': string;
    'val': (attr: any, value: any) => any;
  }
  interface InsSidebarFooterMenu {
    'hideMenu': () => Promise<void>;
    'icon': string;
    'label': string;
    'showMenu': () => Promise<void>;
    'toggleMenu': () => Promise<void>;
    'val': (attr: any, value: any) => any;
  }
  interface InsSidebarItem {
    'activate': () => Promise<void>;
    'activateParent': () => Promise<void>;
    'app': boolean;
    'deactivate': () => Promise<void>;
    'footerLink': string;
    'formatRoute': () => any;
    'hideSubMenu': () => Promise<void>;
    'icon': any;
    'label': string;
    'landingPage': boolean;
    'link': any;
    'routePageHandler': (e: any) => { crumbs: any[]; };
    'showSubMenu': () => Promise<void>;
    'withSubmenu': boolean;
  }
  interface InsSort {
    'cloneOnDrag': boolean;
    'disabled': boolean;
    'draggable': boolean;
    'droppable': boolean;
    'getSortOrder': () => Object;
    'ignoreElements': string;
    'load': (sortable?: any[]) => any[];
    'sort': boolean;
    'sortGroup': string;
    'wrapperClass': string;
  }
  interface InsSparkline {
    'chartData': any;
    'dataSrc': string;
    'description': string;
    'getValue': () => { icon: string; name: string; value: string; percentage: any; description: string; movement: any; sparkline_data: any; data_src: string; };
    'icon': string;
    'movement': any;
    'name': string;
    'percentage': any;
    'reRenderChart': (chartData: any) => Promise<void>;
    'setValue': (data: any) => Promise<void>;
    'val': (attr: any, value: any) => any;
    'value': string;
  }
  interface InsStyleguide {
    'label': string;
  }
  interface InsStyleguideActual {}
  interface InsStyleguideCode {}
  interface InsTab {
    'activateTab': (place: any) => Promise<void>;
    'tabs': any;
  }
  interface InsTabItem {
    'activate': () => Promise<void>;
    'active': boolean;
    'deactivate': () => Promise<void>;
    'disabled': boolean;
    'hasError': boolean;
    'icon': string;
    'label': string;
    'noPadding': boolean;
  }
  interface InsTag {
    'backgroundColor': string;
    'color': string;
    'fontColor': string;
    'fontInherit': boolean;
    'icon': string;
    'label': string;
    'light': boolean;
  }
  interface InsTaggingInput {
    'label': string;
    'name': string;
  }
  interface InsTagsButton {
    'color': string;
    'label': string;
    'outlined': boolean;
    'size': string;
    'solid': boolean;
    'textTransform': string;
  }
  interface InsTextarea {
    'disabled': boolean;
    'errorMessage': string;
    'hasError': boolean;
    'label': string;
    'maxlength': string;
    'name': string;
    'placeholder': string;
    'readonly': boolean;
    'required': boolean;
    'value': string;
  }
  interface InsThumbnail {
    'alt': string;
    'label': string;
    'name': string;
    'src': string;
    'thumbnail': string;
  }
  interface InsTimeline {
    'label': string;
    'loadingScreen': boolean;
    'staticTimeline': boolean;
    'timelineData': any;
  }
  interface InsTimelineItem {
    'color': string;
    'datetime': string;
    'icon': string;
    'inline': boolean;
    'solid': boolean;
    'title': string;
  }
  interface InsTimepicker {
    'disabled': boolean;
    'errorMessage': string;
    'fieldId': string;
    'format': string;
    'hasError': boolean;
    'icon': string;
    'label': string;
    'name': string;
    'placeholder': string;
    'readonly': boolean;
    'required': boolean;
    'value': any;
  }
  interface InsTimezone {
    'label': string;
    'name': string;
  }
  interface InsTitle {
    'class': string;
    'label': string;
  }
  interface InsToggleSwitch {
    'checked': boolean;
    'disabled': boolean;
    'falseValue': string;
    'label': string;
    'name': string;
    'trueValue': string;
    'value': string;
  }
  interface InsTooltip {
    'autoWidth': boolean;
    'background': boolean;
    'closeOnClick': boolean;
    'content': string;
    'html': boolean;
    'icon': any;
    'label': string;
    'position': any;
    'shape': string;
    'trigger': string;
    'width': string;
  }
}

declare global {


  interface HTMLInsAccordionElement extends Components.InsAccordion, HTMLStencilElement {}
  const HTMLInsAccordionElement: {
    prototype: HTMLInsAccordionElement;
    new (): HTMLInsAccordionElement;
  };

  interface HTMLInsAccordionItemElement extends Components.InsAccordionItem, HTMLStencilElement {}
  const HTMLInsAccordionItemElement: {
    prototype: HTMLInsAccordionItemElement;
    new (): HTMLInsAccordionItemElement;
  };

  interface HTMLInsAccordionLinkElement extends Components.InsAccordionLink, HTMLStencilElement {}
  const HTMLInsAccordionLinkElement: {
    prototype: HTMLInsAccordionLinkElement;
    new (): HTMLInsAccordionLinkElement;
  };

  interface HTMLInsAdminElement extends Components.InsAdmin, HTMLStencilElement {}
  const HTMLInsAdminElement: {
    prototype: HTMLInsAdminElement;
    new (): HTMLInsAdminElement;
  };

  interface HTMLInsBackdropElement extends Components.InsBackdrop, HTMLStencilElement {}
  const HTMLInsBackdropElement: {
    prototype: HTMLInsBackdropElement;
    new (): HTMLInsBackdropElement;
  };

  interface HTMLInsBarChartElement extends Components.InsBarChart, HTMLStencilElement {}
  const HTMLInsBarChartElement: {
    prototype: HTMLInsBarChartElement;
    new (): HTMLInsBarChartElement;
  };

  interface HTMLInsBaseTableElement extends Components.InsBaseTable, HTMLStencilElement {}
  const HTMLInsBaseTableElement: {
    prototype: HTMLInsBaseTableElement;
    new (): HTMLInsBaseTableElement;
  };

  interface HTMLInsBaseTableRowElement extends Components.InsBaseTableRow, HTMLStencilElement {}
  const HTMLInsBaseTableRowElement: {
    prototype: HTMLInsBaseTableRowElement;
    new (): HTMLInsBaseTableRowElement;
  };

  interface HTMLInsBaseTableTdElement extends Components.InsBaseTableTd, HTMLStencilElement {}
  const HTMLInsBaseTableTdElement: {
    prototype: HTMLInsBaseTableTdElement;
    new (): HTMLInsBaseTableTdElement;
  };

  interface HTMLInsBaseTableThElement extends Components.InsBaseTableTh, HTMLStencilElement {}
  const HTMLInsBaseTableThElement: {
    prototype: HTMLInsBaseTableThElement;
    new (): HTMLInsBaseTableThElement;
  };

  interface HTMLInsBreadcrumbsElement extends Components.InsBreadcrumbs, HTMLStencilElement {}
  const HTMLInsBreadcrumbsElement: {
    prototype: HTMLInsBreadcrumbsElement;
    new (): HTMLInsBreadcrumbsElement;
  };

  interface HTMLInsButtonElement extends Components.InsButton, HTMLStencilElement {}
  const HTMLInsButtonElement: {
    prototype: HTMLInsButtonElement;
    new (): HTMLInsButtonElement;
  };

  interface HTMLInsButtonGroupElement extends Components.InsButtonGroup, HTMLStencilElement {}
  const HTMLInsButtonGroupElement: {
    prototype: HTMLInsButtonGroupElement;
    new (): HTMLInsButtonGroupElement;
  };

  interface HTMLInsCardElement extends Components.InsCard, HTMLStencilElement {}
  const HTMLInsCardElement: {
    prototype: HTMLInsCardElement;
    new (): HTMLInsCardElement;
  };

  interface HTMLInsCarouselElement extends Components.InsCarousel, HTMLStencilElement {}
  const HTMLInsCarouselElement: {
    prototype: HTMLInsCarouselElement;
    new (): HTMLInsCarouselElement;
  };

  interface HTMLInsCheckboxElement extends Components.InsCheckbox, HTMLStencilElement {}
  const HTMLInsCheckboxElement: {
    prototype: HTMLInsCheckboxElement;
    new (): HTMLInsCheckboxElement;
  };

  interface HTMLInsCheckboxCardElement extends Components.InsCheckboxCard, HTMLStencilElement {}
  const HTMLInsCheckboxCardElement: {
    prototype: HTMLInsCheckboxCardElement;
    new (): HTMLInsCheckboxCardElement;
  };

  interface HTMLInsCodeEditorElement extends Components.InsCodeEditor, HTMLStencilElement {}
  const HTMLInsCodeEditorElement: {
    prototype: HTMLInsCodeEditorElement;
    new (): HTMLInsCodeEditorElement;
  };

  interface HTMLInsContentElement extends Components.InsContent, HTMLStencilElement {}
  const HTMLInsContentElement: {
    prototype: HTMLInsContentElement;
    new (): HTMLInsContentElement;
  };

  interface HTMLInsCreditCardElement extends Components.InsCreditCard, HTMLStencilElement {}
  const HTMLInsCreditCardElement: {
    prototype: HTMLInsCreditCardElement;
    new (): HTMLInsCreditCardElement;
  };

  interface HTMLInsDateTimeElement extends Components.InsDateTime, HTMLStencilElement {}
  const HTMLInsDateTimeElement: {
    prototype: HTMLInsDateTimeElement;
    new (): HTMLInsDateTimeElement;
  };

  interface HTMLInsDatepickerElement extends Components.InsDatepicker, HTMLStencilElement {}
  const HTMLInsDatepickerElement: {
    prototype: HTMLInsDatepickerElement;
    new (): HTMLInsDatepickerElement;
  };

  interface HTMLInsDrawerElement extends Components.InsDrawer, HTMLStencilElement {}
  const HTMLInsDrawerElement: {
    prototype: HTMLInsDrawerElement;
    new (): HTMLInsDrawerElement;
  };

  interface HTMLInsDurationElement extends Components.InsDuration, HTMLStencilElement {}
  const HTMLInsDurationElement: {
    prototype: HTMLInsDurationElement;
    new (): HTMLInsDurationElement;
  };

  interface HTMLInsEditorElement extends Components.InsEditor, HTMLStencilElement {}
  const HTMLInsEditorElement: {
    prototype: HTMLInsEditorElement;
    new (): HTMLInsEditorElement;
  };

  interface HTMLInsFavIconElement extends Components.InsFavIcon, HTMLStencilElement {}
  const HTMLInsFavIconElement: {
    prototype: HTMLInsFavIconElement;
    new (): HTMLInsFavIconElement;
  };

  interface HTMLInsFilterElement extends Components.InsFilter, HTMLStencilElement {}
  const HTMLInsFilterElement: {
    prototype: HTMLInsFilterElement;
    new (): HTMLInsFilterElement;
  };

  interface HTMLInsFilterItemElement extends Components.InsFilterItem, HTMLStencilElement {}
  const HTMLInsFilterItemElement: {
    prototype: HTMLInsFilterItemElement;
    new (): HTMLInsFilterItemElement;
  };

  interface HTMLInsHeaderElement extends Components.InsHeader, HTMLStencilElement {}
  const HTMLInsHeaderElement: {
    prototype: HTMLInsHeaderElement;
    new (): HTMLInsHeaderElement;
  };

  interface HTMLInsHeaderUserElement extends Components.InsHeaderUser, HTMLStencilElement {}
  const HTMLInsHeaderUserElement: {
    prototype: HTMLInsHeaderUserElement;
    new (): HTMLInsHeaderUserElement;
  };

  interface HTMLInsHeadingElement extends Components.InsHeading, HTMLStencilElement {}
  const HTMLInsHeadingElement: {
    prototype: HTMLInsHeadingElement;
    new (): HTMLInsHeadingElement;
  };

  interface HTMLInsImagePickerElement extends Components.InsImagePicker, HTMLStencilElement {}
  const HTMLInsImagePickerElement: {
    prototype: HTMLInsImagePickerElement;
    new (): HTMLInsImagePickerElement;
  };

  interface HTMLInsInfoTableElement extends Components.InsInfoTable, HTMLStencilElement {}
  const HTMLInsInfoTableElement: {
    prototype: HTMLInsInfoTableElement;
    new (): HTMLInsInfoTableElement;
  };

  interface HTMLInsInputElement extends Components.InsInput, HTMLStencilElement {}
  const HTMLInsInputElement: {
    prototype: HTMLInsInputElement;
    new (): HTMLInsInputElement;
  };

  interface HTMLInsInputFileElement extends Components.InsInputFile, HTMLStencilElement {}
  const HTMLInsInputFileElement: {
    prototype: HTMLInsInputFileElement;
    new (): HTMLInsInputFileElement;
  };

  interface HTMLInsInputTelElement extends Components.InsInputTel, HTMLStencilElement {}
  const HTMLInsInputTelElement: {
    prototype: HTMLInsInputTelElement;
    new (): HTMLInsInputTelElement;
  };

  interface HTMLInsInstancesElement extends Components.InsInstances, HTMLStencilElement {}
  const HTMLInsInstancesElement: {
    prototype: HTMLInsInstancesElement;
    new (): HTMLInsInstancesElement;
  };

  interface HTMLInsInstancesItemElement extends Components.InsInstancesItem, HTMLStencilElement {}
  const HTMLInsInstancesItemElement: {
    prototype: HTMLInsInstancesItemElement;
    new (): HTMLInsInstancesItemElement;
  };

  interface HTMLInsInstancesSubItemElement extends Components.InsInstancesSubItem, HTMLStencilElement {}
  const HTMLInsInstancesSubItemElement: {
    prototype: HTMLInsInstancesSubItemElement;
    new (): HTMLInsInstancesSubItemElement;
  };

  interface HTMLInsLineChartElement extends Components.InsLineChart, HTMLStencilElement {}
  const HTMLInsLineChartElement: {
    prototype: HTMLInsLineChartElement;
    new (): HTMLInsLineChartElement;
  };

  interface HTMLInsLoaderElement extends Components.InsLoader, HTMLStencilElement {}
  const HTMLInsLoaderElement: {
    prototype: HTMLInsLoaderElement;
    new (): HTMLInsLoaderElement;
  };

  interface HTMLInsLogoElement extends Components.InsLogo, HTMLStencilElement {}
  const HTMLInsLogoElement: {
    prototype: HTMLInsLogoElement;
    new (): HTMLInsLogoElement;
  };

  interface HTMLInsMarkdownElement extends Components.InsMarkdown, HTMLStencilElement {}
  const HTMLInsMarkdownElement: {
    prototype: HTMLInsMarkdownElement;
    new (): HTMLInsMarkdownElement;
  };

  interface HTMLInsMarkdownEditorElement extends Components.InsMarkdownEditor, HTMLStencilElement {}
  const HTMLInsMarkdownEditorElement: {
    prototype: HTMLInsMarkdownEditorElement;
    new (): HTMLInsMarkdownEditorElement;
  };

  interface HTMLInsModalElement extends Components.InsModal, HTMLStencilElement {}
  const HTMLInsModalElement: {
    prototype: HTMLInsModalElement;
    new (): HTMLInsModalElement;
  };

  interface HTMLInsNotificationsElement extends Components.InsNotifications, HTMLStencilElement {}
  const HTMLInsNotificationsElement: {
    prototype: HTMLInsNotificationsElement;
    new (): HTMLInsNotificationsElement;
  };

  interface HTMLInsNotificationsItemElement extends Components.InsNotificationsItem, HTMLStencilElement {}
  const HTMLInsNotificationsItemElement: {
    prototype: HTMLInsNotificationsItemElement;
    new (): HTMLInsNotificationsItemElement;
  };

  interface HTMLInsPieChartElement extends Components.InsPieChart, HTMLStencilElement {}
  const HTMLInsPieChartElement: {
    prototype: HTMLInsPieChartElement;
    new (): HTMLInsPieChartElement;
  };

  interface HTMLInsProgressBarElement extends Components.InsProgressBar, HTMLStencilElement {}
  const HTMLInsProgressBarElement: {
    prototype: HTMLInsProgressBarElement;
    new (): HTMLInsProgressBarElement;
  };

  interface HTMLInsRadioElement extends Components.InsRadio, HTMLStencilElement {}
  const HTMLInsRadioElement: {
    prototype: HTMLInsRadioElement;
    new (): HTMLInsRadioElement;
  };

  interface HTMLInsRendererElement extends Components.InsRenderer, HTMLStencilElement {}
  const HTMLInsRendererElement: {
    prototype: HTMLInsRendererElement;
    new (): HTMLInsRendererElement;
  };

  interface HTMLInsSearchbarElement extends Components.InsSearchbar, HTMLStencilElement {}
  const HTMLInsSearchbarElement: {
    prototype: HTMLInsSearchbarElement;
    new (): HTMLInsSearchbarElement;
  };

  interface HTMLInsSelectElement extends Components.InsSelect, HTMLStencilElement {}
  const HTMLInsSelectElement: {
    prototype: HTMLInsSelectElement;
    new (): HTMLInsSelectElement;
  };

  interface HTMLInsSelectGroupElement extends Components.InsSelectGroup, HTMLStencilElement {}
  const HTMLInsSelectGroupElement: {
    prototype: HTMLInsSelectGroupElement;
    new (): HTMLInsSelectGroupElement;
  };

  interface HTMLInsSelectOptionElement extends Components.InsSelectOption, HTMLStencilElement {}
  const HTMLInsSelectOptionElement: {
    prototype: HTMLInsSelectOptionElement;
    new (): HTMLInsSelectOptionElement;
  };

  interface HTMLInsSidebarElement extends Components.InsSidebar, HTMLStencilElement {}
  const HTMLInsSidebarElement: {
    prototype: HTMLInsSidebarElement;
    new (): HTMLInsSidebarElement;
  };

  interface HTMLInsSidebarFooterElement extends Components.InsSidebarFooter, HTMLStencilElement {}
  const HTMLInsSidebarFooterElement: {
    prototype: HTMLInsSidebarFooterElement;
    new (): HTMLInsSidebarFooterElement;
  };

  interface HTMLInsSidebarFooterButtonElement extends Components.InsSidebarFooterButton, HTMLStencilElement {}
  const HTMLInsSidebarFooterButtonElement: {
    prototype: HTMLInsSidebarFooterButtonElement;
    new (): HTMLInsSidebarFooterButtonElement;
  };

  interface HTMLInsSidebarFooterMenuElement extends Components.InsSidebarFooterMenu, HTMLStencilElement {}
  const HTMLInsSidebarFooterMenuElement: {
    prototype: HTMLInsSidebarFooterMenuElement;
    new (): HTMLInsSidebarFooterMenuElement;
  };

  interface HTMLInsSidebarItemElement extends Components.InsSidebarItem, HTMLStencilElement {}
  const HTMLInsSidebarItemElement: {
    prototype: HTMLInsSidebarItemElement;
    new (): HTMLInsSidebarItemElement;
  };

  interface HTMLInsSortElement extends Components.InsSort, HTMLStencilElement {}
  const HTMLInsSortElement: {
    prototype: HTMLInsSortElement;
    new (): HTMLInsSortElement;
  };

  interface HTMLInsSparklineElement extends Components.InsSparkline, HTMLStencilElement {}
  const HTMLInsSparklineElement: {
    prototype: HTMLInsSparklineElement;
    new (): HTMLInsSparklineElement;
  };

  interface HTMLInsStyleguideElement extends Components.InsStyleguide, HTMLStencilElement {}
  const HTMLInsStyleguideElement: {
    prototype: HTMLInsStyleguideElement;
    new (): HTMLInsStyleguideElement;
  };

  interface HTMLInsStyleguideActualElement extends Components.InsStyleguideActual, HTMLStencilElement {}
  const HTMLInsStyleguideActualElement: {
    prototype: HTMLInsStyleguideActualElement;
    new (): HTMLInsStyleguideActualElement;
  };

  interface HTMLInsStyleguideCodeElement extends Components.InsStyleguideCode, HTMLStencilElement {}
  const HTMLInsStyleguideCodeElement: {
    prototype: HTMLInsStyleguideCodeElement;
    new (): HTMLInsStyleguideCodeElement;
  };

  interface HTMLInsTabElement extends Components.InsTab, HTMLStencilElement {}
  const HTMLInsTabElement: {
    prototype: HTMLInsTabElement;
    new (): HTMLInsTabElement;
  };

  interface HTMLInsTabItemElement extends Components.InsTabItem, HTMLStencilElement {}
  const HTMLInsTabItemElement: {
    prototype: HTMLInsTabItemElement;
    new (): HTMLInsTabItemElement;
  };

  interface HTMLInsTagElement extends Components.InsTag, HTMLStencilElement {}
  const HTMLInsTagElement: {
    prototype: HTMLInsTagElement;
    new (): HTMLInsTagElement;
  };

  interface HTMLInsTaggingInputElement extends Components.InsTaggingInput, HTMLStencilElement {}
  const HTMLInsTaggingInputElement: {
    prototype: HTMLInsTaggingInputElement;
    new (): HTMLInsTaggingInputElement;
  };

  interface HTMLInsTagsButtonElement extends Components.InsTagsButton, HTMLStencilElement {}
  const HTMLInsTagsButtonElement: {
    prototype: HTMLInsTagsButtonElement;
    new (): HTMLInsTagsButtonElement;
  };

  interface HTMLInsTextareaElement extends Components.InsTextarea, HTMLStencilElement {}
  const HTMLInsTextareaElement: {
    prototype: HTMLInsTextareaElement;
    new (): HTMLInsTextareaElement;
  };

  interface HTMLInsThumbnailElement extends Components.InsThumbnail, HTMLStencilElement {}
  const HTMLInsThumbnailElement: {
    prototype: HTMLInsThumbnailElement;
    new (): HTMLInsThumbnailElement;
  };

  interface HTMLInsTimelineElement extends Components.InsTimeline, HTMLStencilElement {}
  const HTMLInsTimelineElement: {
    prototype: HTMLInsTimelineElement;
    new (): HTMLInsTimelineElement;
  };

  interface HTMLInsTimelineItemElement extends Components.InsTimelineItem, HTMLStencilElement {}
  const HTMLInsTimelineItemElement: {
    prototype: HTMLInsTimelineItemElement;
    new (): HTMLInsTimelineItemElement;
  };

  interface HTMLInsTimepickerElement extends Components.InsTimepicker, HTMLStencilElement {}
  const HTMLInsTimepickerElement: {
    prototype: HTMLInsTimepickerElement;
    new (): HTMLInsTimepickerElement;
  };

  interface HTMLInsTimezoneElement extends Components.InsTimezone, HTMLStencilElement {}
  const HTMLInsTimezoneElement: {
    prototype: HTMLInsTimezoneElement;
    new (): HTMLInsTimezoneElement;
  };

  interface HTMLInsTitleElement extends Components.InsTitle, HTMLStencilElement {}
  const HTMLInsTitleElement: {
    prototype: HTMLInsTitleElement;
    new (): HTMLInsTitleElement;
  };

  interface HTMLInsToggleSwitchElement extends Components.InsToggleSwitch, HTMLStencilElement {}
  const HTMLInsToggleSwitchElement: {
    prototype: HTMLInsToggleSwitchElement;
    new (): HTMLInsToggleSwitchElement;
  };

  interface HTMLInsTooltipElement extends Components.InsTooltip, HTMLStencilElement {}
  const HTMLInsTooltipElement: {
    prototype: HTMLInsTooltipElement;
    new (): HTMLInsTooltipElement;
  };
  interface HTMLElementTagNameMap {
    'ins-accordion': HTMLInsAccordionElement;
    'ins-accordion-item': HTMLInsAccordionItemElement;
    'ins-accordion-link': HTMLInsAccordionLinkElement;
    'ins-admin': HTMLInsAdminElement;
    'ins-backdrop': HTMLInsBackdropElement;
    'ins-bar-chart': HTMLInsBarChartElement;
    'ins-base-table': HTMLInsBaseTableElement;
    'ins-base-table-row': HTMLInsBaseTableRowElement;
    'ins-base-table-td': HTMLInsBaseTableTdElement;
    'ins-base-table-th': HTMLInsBaseTableThElement;
    'ins-breadcrumbs': HTMLInsBreadcrumbsElement;
    'ins-button': HTMLInsButtonElement;
    'ins-button-group': HTMLInsButtonGroupElement;
    'ins-card': HTMLInsCardElement;
    'ins-carousel': HTMLInsCarouselElement;
    'ins-checkbox': HTMLInsCheckboxElement;
    'ins-checkbox-card': HTMLInsCheckboxCardElement;
    'ins-code-editor': HTMLInsCodeEditorElement;
    'ins-content': HTMLInsContentElement;
    'ins-credit-card': HTMLInsCreditCardElement;
    'ins-date-time': HTMLInsDateTimeElement;
    'ins-datepicker': HTMLInsDatepickerElement;
    'ins-drawer': HTMLInsDrawerElement;
    'ins-duration': HTMLInsDurationElement;
    'ins-editor': HTMLInsEditorElement;
    'ins-fav-icon': HTMLInsFavIconElement;
    'ins-filter': HTMLInsFilterElement;
    'ins-filter-item': HTMLInsFilterItemElement;
    'ins-header': HTMLInsHeaderElement;
    'ins-header-user': HTMLInsHeaderUserElement;
    'ins-heading': HTMLInsHeadingElement;
    'ins-image-picker': HTMLInsImagePickerElement;
    'ins-info-table': HTMLInsInfoTableElement;
    'ins-input': HTMLInsInputElement;
    'ins-input-file': HTMLInsInputFileElement;
    'ins-input-tel': HTMLInsInputTelElement;
    'ins-instances': HTMLInsInstancesElement;
    'ins-instances-item': HTMLInsInstancesItemElement;
    'ins-instances-sub-item': HTMLInsInstancesSubItemElement;
    'ins-line-chart': HTMLInsLineChartElement;
    'ins-loader': HTMLInsLoaderElement;
    'ins-logo': HTMLInsLogoElement;
    'ins-markdown': HTMLInsMarkdownElement;
    'ins-markdown-editor': HTMLInsMarkdownEditorElement;
    'ins-modal': HTMLInsModalElement;
    'ins-notifications': HTMLInsNotificationsElement;
    'ins-notifications-item': HTMLInsNotificationsItemElement;
    'ins-pie-chart': HTMLInsPieChartElement;
    'ins-progress-bar': HTMLInsProgressBarElement;
    'ins-radio': HTMLInsRadioElement;
    'ins-renderer': HTMLInsRendererElement;
    'ins-searchbar': HTMLInsSearchbarElement;
    'ins-select': HTMLInsSelectElement;
    'ins-select-group': HTMLInsSelectGroupElement;
    'ins-select-option': HTMLInsSelectOptionElement;
    'ins-sidebar': HTMLInsSidebarElement;
    'ins-sidebar-footer': HTMLInsSidebarFooterElement;
    'ins-sidebar-footer-button': HTMLInsSidebarFooterButtonElement;
    'ins-sidebar-footer-menu': HTMLInsSidebarFooterMenuElement;
    'ins-sidebar-item': HTMLInsSidebarItemElement;
    'ins-sort': HTMLInsSortElement;
    'ins-sparkline': HTMLInsSparklineElement;
    'ins-styleguide': HTMLInsStyleguideElement;
    'ins-styleguide-actual': HTMLInsStyleguideActualElement;
    'ins-styleguide-code': HTMLInsStyleguideCodeElement;
    'ins-tab': HTMLInsTabElement;
    'ins-tab-item': HTMLInsTabItemElement;
    'ins-tag': HTMLInsTagElement;
    'ins-tagging-input': HTMLInsTaggingInputElement;
    'ins-tags-button': HTMLInsTagsButtonElement;
    'ins-textarea': HTMLInsTextareaElement;
    'ins-thumbnail': HTMLInsThumbnailElement;
    'ins-timeline': HTMLInsTimelineElement;
    'ins-timeline-item': HTMLInsTimelineItemElement;
    'ins-timepicker': HTMLInsTimepickerElement;
    'ins-timezone': HTMLInsTimezoneElement;
    'ins-title': HTMLInsTitleElement;
    'ins-toggle-switch': HTMLInsToggleSwitchElement;
    'ins-tooltip': HTMLInsTooltipElement;
  }
}

declare namespace LocalJSX {
  interface InsAccordion {
    'defaultOpen'?: number;
    'menu'?: boolean;
    'onToggle'?: (event: CustomEvent<any>) => void;
  }
  interface InsAccordionItem {
    'active'?: boolean;
    'arrowActivated'?: boolean;
    'disabled'?: boolean;
    'heading'?: string;
    'icon'?: string;
    'link'?: string;
    'linkTarget'?: string;
  }
  interface InsAccordionLink {
    'active'?: boolean;
    'disabled'?: boolean;
    'icon'?: string;
    'label'?: string;
    'link'?: string;
    'linkTarget'?: string;
    'linkTitle'?: string;
  }
  interface InsAdmin {}
  interface InsBackdrop {
    'light'?: boolean;
  }
  interface InsBarChart {
    'categories'?: Array<any>;
    'chartData'?: Array<any>;
    'dataSrc'?: string;
    'horizontal'?: boolean;
    'name'?: string;
    'stacked'?: boolean;
  }
  interface InsBaseTable {
    'bulkActions'?: any;
    'currency'?: string;
    'defaultBulkAction'?: string;
    'emptyValue'?: string;
    'heading'?: string;
    'initialSearch'?: string;
    'loaderIcon'?: any;
    'loaderMessage'?: any;
    'loaderTitle'?: any;
    'loadingScreen'?: boolean;
    'noWrap'?: boolean;
    'onOnFieldChange'?: (event: CustomEvent<any>) => void;
    'onOnPaginationChange'?: (event: CustomEvent<any>) => void;
    'onOnTableBulkAction'?: (event: CustomEvent<any>) => void;
    'onOnTableRowAction'?: (event: CustomEvent<any>) => void;
    'onOnTableSearch'?: (event: CustomEvent<any>) => void;
    'onOnTableSort'?: (event: CustomEvent<any>) => void;
    'pageNumber'?: number;
    'pageSize'?: number;
    'pageSizeOptions'?: any;
    'paginationText'?: string;
    'rowActions'?: any;
    'searchPosition'?: string;
    'searchbarPlaceholder'?: string;
    'selectedRows'?: any;
    'sortKeyword'?: string;
    'sortOrder'?: boolean;
    'staticTable'?: boolean;
    'tableData'?: any;
    'tableHeaders'?: any;
    'textOverflow'?: string;
    'totalCount'?: any;
    'updatedRows'?: any;
    'withoutPagination'?: boolean;
    'withoutSearch'?: boolean;
  }
  interface InsBaseTableRow {}
  interface InsBaseTableTd {}
  interface InsBaseTableTh {}
  interface InsBreadcrumbs {
    'onRoutePage'?: (event: CustomEvent<any>) => void;
  }
  interface InsButton {
    'color'?: string;
    'cursor'?: string;
    'data'?: string;
    'disabled'?: boolean;
    'dropdown'?: boolean;
    'icon'?: string;
    'label'?: string;
    'loading'?: boolean;
    'onOnClickInsButton'?: (event: CustomEvent<any>) => void;
    'onOnClickInsButtonOption'?: (event: CustomEvent<any>) => void;
    'options'?: string;
    'outlined'?: boolean;
    'size'?: string;
    'solid'?: boolean;
    'textTransform'?: string;
    'type'?: string;
  }
  interface InsButtonGroup {
    'activeIndex'?: number;
    'activeOption'?: string;
    'color'?: string;
    'disabled'?: boolean;
    'onOnButtonAction'?: (event: CustomEvent<any>) => void;
    'options'?: string;
    'size'?: string;
  }
  interface InsCard {
    'noPadding'?: boolean;
    'outlined'?: boolean;
    'steady'?: boolean;
  }
  interface InsCarousel {
    'autoplay'?: boolean;
    'bindTo'?: string;
    'bodyText'?: string;
    'ctaColor'?: string;
    'ctaDisabled'?: boolean;
    'ctaLabel'?: string;
    'ctaLink'?: string;
    'ctaLinkTarget'?: string;
    'duration'?: number;
    'heading'?: string;
    'height'?: string;
    'layout'?: number;
    'loop'?: boolean;
    'noCarouselButton'?: boolean;
    'noPagination'?: boolean;
    'onSlide'?: (event: CustomEvent<any>) => void;
    'perPage'?: number;
    'startIndex'?: number;
    'subHeading'?: string;
    'transition'?: number;
    'width'?: string;
  }
  interface InsCheckbox {
    'checked'?: boolean;
    'disabled'?: boolean;
    'falseValue'?: string;
    'label'?: string;
    'name'?: string;
    'onOnCheckInsCheckbox'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'trueValue'?: string;
    'value'?: string;
  }
  interface InsCheckboxCard {
    'disabled'?: boolean;
    'label'?: string;
    'name'?: string;
    'noPadding'?: boolean;
    'onOnClickInsCheckboxCard'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'selected'?: boolean;
    'selectedColor'?: string;
    'tabOrder'?: string;
    'value'?: string;
  }
  interface InsCodeEditor {
    'disableLineNumbers'?: boolean;
    'errorMessage'?: string;
    'hasError'?: boolean;
    'label'?: string;
    'mode'?: string;
    'name'?: string;
    'onOnblur'?: (event: CustomEvent<any>) => void;
    'onOninput'?: (event: CustomEvent<any>) => void;
    'readonly'?: boolean;
    'theme'?: string;
    'value'?: string;
  }
  interface InsContent {}
  interface InsCreditCard {
    'active'?: boolean;
    'brand'?: string;
    'expired'?: boolean;
    'expiryMonth'?: string;
    'expiryYear'?: string;
    'fullYear'?: boolean;
    'lastFour'?: string;
    'onInsCreditCardClicked'?: (event: CustomEvent<any>) => void;
    'onInsCreditCardClosed'?: (event: CustomEvent<any>) => void;
    'value'?: string;
  }
  interface InsDateTime {
    'disabled'?: boolean;
    'errorMessage'?: string;
    'format'?: string;
    'hasError'?: boolean;
    'icon'?: string;
    'label'?: string;
    'maxDate'?: string;
    'minDate'?: string;
    'name'?: string;
    'noMeridiem'?: boolean;
    'onOnpick'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'readonly'?: boolean;
    'value'?: string;
  }
  interface InsDatepicker {
    'disabled'?: boolean;
    'errorMessage'?: string;
    'format'?: string;
    'hasError'?: boolean;
    'icon'?: string;
    'label'?: string;
    'maxDate'?: string;
    'minDate'?: string;
    'name'?: string;
    'onOnDateChange'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'readonly'?: boolean;
    'value'?: string;
  }
  interface InsDrawer {
    'backdropCanClose'?: boolean;
    'bordered'?: boolean;
    'customWidth'?: string;
    'icon'?: string;
    'isOpen'?: boolean;
    'label'?: string;
    'noPadding'?: boolean;
    'onToggleDrawer'?: (event: CustomEvent<any>) => void;
    'position'?: string;
    'showCloseButton'?: boolean;
    'showHeader'?: boolean;
    'stickyHeader'?: boolean;
  }
  interface InsDuration {
    'label'?: string;
    'name'?: string;
  }
  interface InsEditor {
    'classId'?: string;
    'disableLineNumbers'?: boolean;
    'errorMessage'?: string;
    'hasCodeEditor'?: boolean;
    'hasError'?: boolean;
    'imageUpload'?: boolean;
    'images'?: string;
    'label'?: string;
    'mode'?: string;
    'name'?: string;
    'onOnblur'?: (event: CustomEvent<any>) => void;
    'onOninput'?: (event: CustomEvent<any>) => void;
    'onOnupload'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'pluginsList'?: any;
    'readonly'?: boolean;
    'showSource'?: boolean;
    'theme'?: string;
    'value'?: string;
  }
  interface InsFavIcon {
    'buttonColor'?: string;
    'type'?: string;
  }
  interface InsFilter {
    'dateFrom'?: string;
    'dateOpt'?: any;
    'dateTitle'?: any;
    'dateTo'?: string;
    'defaultDate'?: string;
    'onOnDateFilterApply'?: (event: CustomEvent<any>) => void;
    'onOnFilterApply'?: (event: CustomEvent<any>) => void;
    'withDateFilter'?: boolean;
  }
  interface InsFilterItem {
    'name'?: string;
    'onOnFilter'?: (event: CustomEvent<any>) => void;
    'options'?: any;
    'selected'?: any;
  }
  interface InsHeader {
    'hasMenuToggle'?: boolean;
    'supportLink'?: string;
  }
  interface InsHeaderUser {
    'app'?: boolean;
    'formattedRoute'?: string;
    'logoutLink'?: string;
    'name'?: string;
    'onRoutePage'?: (event: CustomEvent<any>) => void;
    'profileLink'?: string;
  }
  interface InsHeading {
    'backgroundColor'?: string;
    'editable'?: boolean;
    'label'?: string;
    'level'?: number;
    'maxlength'?: string;
    'name'?: string;
    'onOnInsHeadingUpdate'?: (event: CustomEvent<any>) => void;
    'withoutLine'?: boolean;
  }
  interface InsImagePicker {
    'buttonColor'?: string;
    'fileName'?: any;
    'imgType'?: string;
    'label'?: string;
    'name'?: string;
    'notImageFile'?: boolean;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'uploadImgContainer'?: string;
    'uploadImgRecFileSize'?: number;
    'uploadImgRecHeight'?: number;
    'uploadImgRecWidth'?: number;
    'value'?: any;
  }
  interface InsInfoTable {
    'emptyValue'?: string;
    'heading'?: string;
    'loaderIcon'?: any;
    'loaderMessage'?: any;
    'loaderTitle'?: any;
    'loadingScreen'?: boolean;
    'noWrap'?: boolean;
    'renderHtml'?: boolean;
    'tableData'?: any;
    'textOverflow'?: string;
  }
  interface InsInput {
    'activated'?: boolean;
    'disabled'?: boolean;
    'errorMessage'?: string;
    'field'?: string;
    'fieldId'?: string;
    'hasError'?: boolean;
    'icon'?: string;
    'label'?: string;
    'max'?: string;
    'maxlength'?: string;
    'min'?: string;
    'name'?: string;
    'onOnblur'?: (event: CustomEvent<any>) => void;
    'onOninput'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'readonly'?: boolean;
    'required'?: boolean;
    'step'?: string;
    'value'?: string;
  }
  interface InsInputFile {
    'acceptedFiles'?: string;
    'disabled'?: boolean;
    'errorMessage'?: string;
    'fileIcon'?: string;
    'hasError'?: boolean;
    'label'?: string;
    'maxFileSize'?: number;
    'maxFileSizeLabel'?: string;
    'maxFiles'?: number;
    'maxFilesLabel'?: string;
    'name'?: string;
    'onFileAdded'?: (event: CustomEvent<any>) => void;
    'onFileError'?: (event: CustomEvent<any>) => void;
    'onFileRemoved'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'required'?: boolean;
    'showLimit'?: boolean;
    'value'?: any;
  }
  interface InsInputTel {
    'areaCode'?: string;
    'areacodePlaceholder'?: string;
    'areacodeValue'?: string;
    'countryCode'?: string;
    'disabled'?: boolean;
    'errorMessage'?: string;
    'hasError'?: boolean;
    'label'?: string;
    'noAreacode'?: boolean;
    'onInsInputTelChange'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'phoneNumber'?: string;
    'phonenumPlaceholder'?: string;
    'phonenumValue'?: string;
    'readonly'?: boolean;
    'required'?: boolean;
  }
  interface InsInstances {
    'instance'?: string;
    'instanceLink'?: string;
    'logoLink'?: string;
    'newTab'?: boolean;
  }
  interface InsInstancesItem {
    'instance'?: string;
    'instanceLink'?: string;
    'logoLink'?: string;
    'onActiveSubItem'?: (event: CustomEvent<any>) => void;
    'onRouteInstance'?: (event: CustomEvent<any>) => void;
    'withSubItem'?: boolean;
  }
  interface InsInstancesSubItem {
    'instance'?: string;
    'link'?: string;
    'onRouteInstanceSubItem'?: (event: CustomEvent<any>) => void;
  }
  interface InsLineChart {
    'categories'?: any;
    'chartData'?: any;
    'dataSrc'?: string;
    'name'?: string;
  }
  interface InsLoader {
    'iconColor'?: string;
    'imageSource'?: string;
    'stateIcon'?: string;
    'stateMessage'?: string;
    'stateTitle'?: string;
    'useImage'?: boolean;
  }
  interface InsLogo {
    'buttonColor'?: string;
    'type'?: string;
  }
  interface InsMarkdown {
    'label'?: string;
    'value'?: string;
  }
  interface InsMarkdownEditor {
    'errorMessage'?: string;
    'hasError'?: boolean;
    'label'?: string;
    'name'?: string;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'readonly'?: boolean;
    'required'?: boolean;
    'value'?: string;
  }
  interface InsModal {
    'buttonAlignment'?: string;
    'childModal'?: any;
    'closeButtonColor'?: string;
    'closeButtonIcon'?: string;
    'closeButtonLabel'?: string;
    'confirmButtonColor'?: string;
    'confirmButtonIcon'?: string;
    'confirmButtonLabel'?: string;
    'confirmation'?: boolean;
    'heading'?: string;
    'height'?: string;
    'light'?: boolean;
    'noButton'?: boolean;
    'onOnInsModalClose'?: (event: CustomEvent<any>) => void;
    'parentRender'?: string;
    'preventClickOutside'?: boolean;
    'value'?: any;
    'width'?: string;
    'withBackdrop'?: boolean;
  }
  interface InsNotifications {}
  interface InsNotificationsItem {
    'desc'?: string;
    'duration'?: string;
    'eventType'?: string;
    'heading'?: string;
    'icon'?: string;
    'link'?: string;
    'linkLabel'?: string;
    'status'?: string;
  }
  interface InsPieChart {
    'chartData'?: Array<any>;
    'colors'?: Array<any>;
    'dataLabels'?: boolean;
    'endAngle'?: number;
    'fillColor'?: string;
    'innerSize'?: string;
    'innerTitle'?: boolean;
    'legends'?: boolean;
    'size'?: string;
    'startAngle'?: number;
    'title'?: string;
    'titleOffset'?: number;
  }
  interface InsProgressBar {
    'hidden'?: boolean;
    'progress'?: number;
    'text'?: string;
    'total'?: number;
  }
  interface InsRadio {
    'checked'?: boolean;
    'disabled'?: boolean;
    'label'?: any;
    'name'?: any;
    'onOnSelect'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'staticValue'?: any;
    'value'?: any;
  }
  interface InsRenderer {
    'app'?: boolean;
    'label'?: string;
    'link'?: string;
    'route'?: any;
  }
  interface InsSearchbar {
    'isSearching'?: boolean;
    'name'?: string;
    'onOnSearch'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'value'?: string;
  }
  interface InsSelect {
    'button'?: boolean;
    'buttonLabel'?: string;
    'disabled'?: boolean;
    'dropUp'?: boolean;
    'dynamicPlaceholder'?: string;
    'dynamicSearch'?: boolean;
    'errorMessage'?: string;
    'hasError'?: boolean;
    'infiniteScroll'?: boolean;
    'initializing'?: boolean;
    'label'?: string;
    'multiple'?: boolean;
    'name'?: string;
    'onLoadMore'?: (event: CustomEvent<any>) => void;
    'onOnOptionSelect'?: (event: CustomEvent<any>) => void;
    'onOnSearch'?: (event: CustomEvent<any>) => void;
    'onOnSubmitOption'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'readonly'?: boolean;
    'searchable'?: boolean;
    'selected_values'?: any;
    'small'?: boolean;
    'value'?: any;
    'withDynamicOption'?: boolean;
  }
  interface InsSelectGroup {
    'label'?: string;
  }
  interface InsSelectOption {
    'default'?: boolean;
    'disabled'?: boolean;
    'label'?: string;
    'onDefaultEvent'?: (event: CustomEvent<any>) => void;
    'onInsSelectOptionClicked'?: (event: CustomEvent<any>) => void;
    'value'?: string;
  }
  interface InsSidebar {
    'fullLogo'?: string;
    'iconLogo'?: string;
    'onSidebarAction'?: (event: CustomEvent<any>) => void;
  }
  interface InsSidebarFooter {}
  interface InsSidebarFooterButton {
    'icon'?: string;
    'onInsSidebarFooterButtonEvent'?: (event: CustomEvent<any>) => void;
    'open'?: string;
  }
  interface InsSidebarFooterMenu {
    'icon'?: string;
    'label'?: string;
  }
  interface InsSidebarItem {
    'app'?: boolean;
    'footerLink'?: string;
    'icon'?: any;
    'label'?: string;
    'landingPage'?: boolean;
    'link'?: any;
    'onRoutePage'?: (event: CustomEvent<any>) => void;
    'withSubmenu'?: boolean;
  }
  interface InsSort {
    'cloneOnDrag'?: boolean;
    'disabled'?: boolean;
    'draggable'?: boolean;
    'droppable'?: boolean;
    'ignoreElements'?: string;
    'onOnAdd'?: (event: CustomEvent<Object>) => void;
    'onOnChoose'?: (event: CustomEvent<Object>) => void;
    'onOnClone'?: (event: CustomEvent<Object>) => void;
    'onOnDragEnd'?: (event: CustomEvent<Object>) => void;
    'onOnDragStart'?: (event: CustomEvent<Object>) => void;
    'onOnDrop'?: (event: CustomEvent<Object>) => void;
    'onOnMove'?: (event: CustomEvent<Object>) => void;
    'onOnPositionChanged'?: (event: CustomEvent<Object>) => void;
    'onOnRemove'?: (event: CustomEvent<Object>) => void;
    'onOnUpdate'?: (event: CustomEvent<Object>) => void;
    'sort'?: boolean;
    'sortGroup'?: string;
    'wrapperClass'?: string;
  }
  interface InsSparkline {
    'chartData'?: any;
    'dataSrc'?: string;
    'description'?: string;
    'icon'?: string;
    'movement'?: any;
    'name'?: string;
    'percentage'?: any;
    'value'?: string;
  }
  interface InsStyleguide {
    'label'?: string;
  }
  interface InsStyleguideActual {}
  interface InsStyleguideCode {}
  interface InsTab {
    'onOnchangeTab'?: (event: CustomEvent<any>) => void;
    'tabs'?: any;
  }
  interface InsTabItem {
    'active'?: boolean;
    'disabled'?: boolean;
    'hasError'?: boolean;
    'icon'?: string;
    'label'?: string;
    'noPadding'?: boolean;
    'onTabItemDisableToggled'?: (event: CustomEvent<any>) => void;
    'onTabItemError'?: (event: CustomEvent<any>) => void;
  }
  interface InsTag {
    'backgroundColor'?: string;
    'color'?: string;
    'fontColor'?: string;
    'fontInherit'?: boolean;
    'icon'?: string;
    'label'?: string;
    'light'?: boolean;
  }
  interface InsTaggingInput {
    'label'?: string;
    'name'?: string;
  }
  interface InsTagsButton {
    'color'?: string;
    'label'?: string;
    'outlined'?: boolean;
    'size'?: string;
    'solid'?: boolean;
    'textTransform'?: string;
  }
  interface InsTextarea {
    'disabled'?: boolean;
    'errorMessage'?: string;
    'hasError'?: boolean;
    'label'?: string;
    'maxlength'?: string;
    'name'?: string;
    'onOninput'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'readonly'?: boolean;
    'required'?: boolean;
    'value'?: string;
  }
  interface InsThumbnail {
    'alt'?: string;
    'label'?: string;
    'name'?: string;
    'src'?: string;
    'thumbnail'?: string;
  }
  interface InsTimeline {
    'label'?: string;
    'loadingScreen'?: boolean;
    'onPaginationChange'?: (event: CustomEvent<any>) => void;
    'staticTimeline'?: boolean;
    'timelineData'?: any;
  }
  interface InsTimelineItem {
    'color'?: string;
    'datetime'?: string;
    'icon'?: string;
    'inline'?: boolean;
    'solid'?: boolean;
    'title'?: string;
  }
  interface InsTimepicker {
    'disabled'?: boolean;
    'errorMessage'?: string;
    'fieldId'?: string;
    'format'?: string;
    'hasError'?: boolean;
    'icon'?: string;
    'label'?: string;
    'name'?: string;
    'onOnblur'?: (event: CustomEvent<any>) => void;
    'onOninput'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'readonly'?: boolean;
    'required'?: boolean;
    'value'?: any;
  }
  interface InsTimezone {
    'label'?: string;
    'name'?: string;
  }
  interface InsTitle {
    'class'?: string;
    'label'?: string;
  }
  interface InsToggleSwitch {
    'checked'?: boolean;
    'disabled'?: boolean;
    'falseValue'?: string;
    'label'?: string;
    'name'?: string;
    'onOnCheckInsToggleSwitch'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'trueValue'?: string;
    'value'?: string;
  }
  interface InsTooltip {
    'autoWidth'?: boolean;
    'background'?: boolean;
    'closeOnClick'?: boolean;
    'content'?: string;
    'html'?: boolean;
    'icon'?: any;
    'label'?: string;
    'onShowTooltip'?: (event: CustomEvent<any>) => void;
    'position'?: any;
    'shape'?: string;
    'trigger'?: string;
    'width'?: string;
  }

  interface IntrinsicElements {
    'ins-accordion': InsAccordion;
    'ins-accordion-item': InsAccordionItem;
    'ins-accordion-link': InsAccordionLink;
    'ins-admin': InsAdmin;
    'ins-backdrop': InsBackdrop;
    'ins-bar-chart': InsBarChart;
    'ins-base-table': InsBaseTable;
    'ins-base-table-row': InsBaseTableRow;
    'ins-base-table-td': InsBaseTableTd;
    'ins-base-table-th': InsBaseTableTh;
    'ins-breadcrumbs': InsBreadcrumbs;
    'ins-button': InsButton;
    'ins-button-group': InsButtonGroup;
    'ins-card': InsCard;
    'ins-carousel': InsCarousel;
    'ins-checkbox': InsCheckbox;
    'ins-checkbox-card': InsCheckboxCard;
    'ins-code-editor': InsCodeEditor;
    'ins-content': InsContent;
    'ins-credit-card': InsCreditCard;
    'ins-date-time': InsDateTime;
    'ins-datepicker': InsDatepicker;
    'ins-drawer': InsDrawer;
    'ins-duration': InsDuration;
    'ins-editor': InsEditor;
    'ins-fav-icon': InsFavIcon;
    'ins-filter': InsFilter;
    'ins-filter-item': InsFilterItem;
    'ins-header': InsHeader;
    'ins-header-user': InsHeaderUser;
    'ins-heading': InsHeading;
    'ins-image-picker': InsImagePicker;
    'ins-info-table': InsInfoTable;
    'ins-input': InsInput;
    'ins-input-file': InsInputFile;
    'ins-input-tel': InsInputTel;
    'ins-instances': InsInstances;
    'ins-instances-item': InsInstancesItem;
    'ins-instances-sub-item': InsInstancesSubItem;
    'ins-line-chart': InsLineChart;
    'ins-loader': InsLoader;
    'ins-logo': InsLogo;
    'ins-markdown': InsMarkdown;
    'ins-markdown-editor': InsMarkdownEditor;
    'ins-modal': InsModal;
    'ins-notifications': InsNotifications;
    'ins-notifications-item': InsNotificationsItem;
    'ins-pie-chart': InsPieChart;
    'ins-progress-bar': InsProgressBar;
    'ins-radio': InsRadio;
    'ins-renderer': InsRenderer;
    'ins-searchbar': InsSearchbar;
    'ins-select': InsSelect;
    'ins-select-group': InsSelectGroup;
    'ins-select-option': InsSelectOption;
    'ins-sidebar': InsSidebar;
    'ins-sidebar-footer': InsSidebarFooter;
    'ins-sidebar-footer-button': InsSidebarFooterButton;
    'ins-sidebar-footer-menu': InsSidebarFooterMenu;
    'ins-sidebar-item': InsSidebarItem;
    'ins-sort': InsSort;
    'ins-sparkline': InsSparkline;
    'ins-styleguide': InsStyleguide;
    'ins-styleguide-actual': InsStyleguideActual;
    'ins-styleguide-code': InsStyleguideCode;
    'ins-tab': InsTab;
    'ins-tab-item': InsTabItem;
    'ins-tag': InsTag;
    'ins-tagging-input': InsTaggingInput;
    'ins-tags-button': InsTagsButton;
    'ins-textarea': InsTextarea;
    'ins-thumbnail': InsThumbnail;
    'ins-timeline': InsTimeline;
    'ins-timeline-item': InsTimelineItem;
    'ins-timepicker': InsTimepicker;
    'ins-timezone': InsTimezone;
    'ins-title': InsTitle;
    'ins-toggle-switch': InsToggleSwitch;
    'ins-tooltip': InsTooltip;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ins-accordion': LocalJSX.InsAccordion & JSXBase.HTMLAttributes<HTMLInsAccordionElement>;
      'ins-accordion-item': LocalJSX.InsAccordionItem & JSXBase.HTMLAttributes<HTMLInsAccordionItemElement>;
      'ins-accordion-link': LocalJSX.InsAccordionLink & JSXBase.HTMLAttributes<HTMLInsAccordionLinkElement>;
      'ins-admin': LocalJSX.InsAdmin & JSXBase.HTMLAttributes<HTMLInsAdminElement>;
      'ins-backdrop': LocalJSX.InsBackdrop & JSXBase.HTMLAttributes<HTMLInsBackdropElement>;
      'ins-bar-chart': LocalJSX.InsBarChart & JSXBase.HTMLAttributes<HTMLInsBarChartElement>;
      'ins-base-table': LocalJSX.InsBaseTable & JSXBase.HTMLAttributes<HTMLInsBaseTableElement>;
      'ins-base-table-row': LocalJSX.InsBaseTableRow & JSXBase.HTMLAttributes<HTMLInsBaseTableRowElement>;
      'ins-base-table-td': LocalJSX.InsBaseTableTd & JSXBase.HTMLAttributes<HTMLInsBaseTableTdElement>;
      'ins-base-table-th': LocalJSX.InsBaseTableTh & JSXBase.HTMLAttributes<HTMLInsBaseTableThElement>;
      'ins-breadcrumbs': LocalJSX.InsBreadcrumbs & JSXBase.HTMLAttributes<HTMLInsBreadcrumbsElement>;
      'ins-button': LocalJSX.InsButton & JSXBase.HTMLAttributes<HTMLInsButtonElement>;
      'ins-button-group': LocalJSX.InsButtonGroup & JSXBase.HTMLAttributes<HTMLInsButtonGroupElement>;
      'ins-card': LocalJSX.InsCard & JSXBase.HTMLAttributes<HTMLInsCardElement>;
      'ins-carousel': LocalJSX.InsCarousel & JSXBase.HTMLAttributes<HTMLInsCarouselElement>;
      'ins-checkbox': LocalJSX.InsCheckbox & JSXBase.HTMLAttributes<HTMLInsCheckboxElement>;
      'ins-checkbox-card': LocalJSX.InsCheckboxCard & JSXBase.HTMLAttributes<HTMLInsCheckboxCardElement>;
      'ins-code-editor': LocalJSX.InsCodeEditor & JSXBase.HTMLAttributes<HTMLInsCodeEditorElement>;
      'ins-content': LocalJSX.InsContent & JSXBase.HTMLAttributes<HTMLInsContentElement>;
      'ins-credit-card': LocalJSX.InsCreditCard & JSXBase.HTMLAttributes<HTMLInsCreditCardElement>;
      'ins-date-time': LocalJSX.InsDateTime & JSXBase.HTMLAttributes<HTMLInsDateTimeElement>;
      'ins-datepicker': LocalJSX.InsDatepicker & JSXBase.HTMLAttributes<HTMLInsDatepickerElement>;
      'ins-drawer': LocalJSX.InsDrawer & JSXBase.HTMLAttributes<HTMLInsDrawerElement>;
      'ins-duration': LocalJSX.InsDuration & JSXBase.HTMLAttributes<HTMLInsDurationElement>;
      'ins-editor': LocalJSX.InsEditor & JSXBase.HTMLAttributes<HTMLInsEditorElement>;
      'ins-fav-icon': LocalJSX.InsFavIcon & JSXBase.HTMLAttributes<HTMLInsFavIconElement>;
      'ins-filter': LocalJSX.InsFilter & JSXBase.HTMLAttributes<HTMLInsFilterElement>;
      'ins-filter-item': LocalJSX.InsFilterItem & JSXBase.HTMLAttributes<HTMLInsFilterItemElement>;
      'ins-header': LocalJSX.InsHeader & JSXBase.HTMLAttributes<HTMLInsHeaderElement>;
      'ins-header-user': LocalJSX.InsHeaderUser & JSXBase.HTMLAttributes<HTMLInsHeaderUserElement>;
      'ins-heading': LocalJSX.InsHeading & JSXBase.HTMLAttributes<HTMLInsHeadingElement>;
      'ins-image-picker': LocalJSX.InsImagePicker & JSXBase.HTMLAttributes<HTMLInsImagePickerElement>;
      'ins-info-table': LocalJSX.InsInfoTable & JSXBase.HTMLAttributes<HTMLInsInfoTableElement>;
      'ins-input': LocalJSX.InsInput & JSXBase.HTMLAttributes<HTMLInsInputElement>;
      'ins-input-file': LocalJSX.InsInputFile & JSXBase.HTMLAttributes<HTMLInsInputFileElement>;
      'ins-input-tel': LocalJSX.InsInputTel & JSXBase.HTMLAttributes<HTMLInsInputTelElement>;
      'ins-instances': LocalJSX.InsInstances & JSXBase.HTMLAttributes<HTMLInsInstancesElement>;
      'ins-instances-item': LocalJSX.InsInstancesItem & JSXBase.HTMLAttributes<HTMLInsInstancesItemElement>;
      'ins-instances-sub-item': LocalJSX.InsInstancesSubItem & JSXBase.HTMLAttributes<HTMLInsInstancesSubItemElement>;
      'ins-line-chart': LocalJSX.InsLineChart & JSXBase.HTMLAttributes<HTMLInsLineChartElement>;
      'ins-loader': LocalJSX.InsLoader & JSXBase.HTMLAttributes<HTMLInsLoaderElement>;
      'ins-logo': LocalJSX.InsLogo & JSXBase.HTMLAttributes<HTMLInsLogoElement>;
      'ins-markdown': LocalJSX.InsMarkdown & JSXBase.HTMLAttributes<HTMLInsMarkdownElement>;
      'ins-markdown-editor': LocalJSX.InsMarkdownEditor & JSXBase.HTMLAttributes<HTMLInsMarkdownEditorElement>;
      'ins-modal': LocalJSX.InsModal & JSXBase.HTMLAttributes<HTMLInsModalElement>;
      'ins-notifications': LocalJSX.InsNotifications & JSXBase.HTMLAttributes<HTMLInsNotificationsElement>;
      'ins-notifications-item': LocalJSX.InsNotificationsItem & JSXBase.HTMLAttributes<HTMLInsNotificationsItemElement>;
      'ins-pie-chart': LocalJSX.InsPieChart & JSXBase.HTMLAttributes<HTMLInsPieChartElement>;
      'ins-progress-bar': LocalJSX.InsProgressBar & JSXBase.HTMLAttributes<HTMLInsProgressBarElement>;
      'ins-radio': LocalJSX.InsRadio & JSXBase.HTMLAttributes<HTMLInsRadioElement>;
      'ins-renderer': LocalJSX.InsRenderer & JSXBase.HTMLAttributes<HTMLInsRendererElement>;
      'ins-searchbar': LocalJSX.InsSearchbar & JSXBase.HTMLAttributes<HTMLInsSearchbarElement>;
      'ins-select': LocalJSX.InsSelect & JSXBase.HTMLAttributes<HTMLInsSelectElement>;
      'ins-select-group': LocalJSX.InsSelectGroup & JSXBase.HTMLAttributes<HTMLInsSelectGroupElement>;
      'ins-select-option': LocalJSX.InsSelectOption & JSXBase.HTMLAttributes<HTMLInsSelectOptionElement>;
      'ins-sidebar': LocalJSX.InsSidebar & JSXBase.HTMLAttributes<HTMLInsSidebarElement>;
      'ins-sidebar-footer': LocalJSX.InsSidebarFooter & JSXBase.HTMLAttributes<HTMLInsSidebarFooterElement>;
      'ins-sidebar-footer-button': LocalJSX.InsSidebarFooterButton & JSXBase.HTMLAttributes<HTMLInsSidebarFooterButtonElement>;
      'ins-sidebar-footer-menu': LocalJSX.InsSidebarFooterMenu & JSXBase.HTMLAttributes<HTMLInsSidebarFooterMenuElement>;
      'ins-sidebar-item': LocalJSX.InsSidebarItem & JSXBase.HTMLAttributes<HTMLInsSidebarItemElement>;
      'ins-sort': LocalJSX.InsSort & JSXBase.HTMLAttributes<HTMLInsSortElement>;
      'ins-sparkline': LocalJSX.InsSparkline & JSXBase.HTMLAttributes<HTMLInsSparklineElement>;
      'ins-styleguide': LocalJSX.InsStyleguide & JSXBase.HTMLAttributes<HTMLInsStyleguideElement>;
      'ins-styleguide-actual': LocalJSX.InsStyleguideActual & JSXBase.HTMLAttributes<HTMLInsStyleguideActualElement>;
      'ins-styleguide-code': LocalJSX.InsStyleguideCode & JSXBase.HTMLAttributes<HTMLInsStyleguideCodeElement>;
      'ins-tab': LocalJSX.InsTab & JSXBase.HTMLAttributes<HTMLInsTabElement>;
      'ins-tab-item': LocalJSX.InsTabItem & JSXBase.HTMLAttributes<HTMLInsTabItemElement>;
      'ins-tag': LocalJSX.InsTag & JSXBase.HTMLAttributes<HTMLInsTagElement>;
      'ins-tagging-input': LocalJSX.InsTaggingInput & JSXBase.HTMLAttributes<HTMLInsTaggingInputElement>;
      'ins-tags-button': LocalJSX.InsTagsButton & JSXBase.HTMLAttributes<HTMLInsTagsButtonElement>;
      'ins-textarea': LocalJSX.InsTextarea & JSXBase.HTMLAttributes<HTMLInsTextareaElement>;
      'ins-thumbnail': LocalJSX.InsThumbnail & JSXBase.HTMLAttributes<HTMLInsThumbnailElement>;
      'ins-timeline': LocalJSX.InsTimeline & JSXBase.HTMLAttributes<HTMLInsTimelineElement>;
      'ins-timeline-item': LocalJSX.InsTimelineItem & JSXBase.HTMLAttributes<HTMLInsTimelineItemElement>;
      'ins-timepicker': LocalJSX.InsTimepicker & JSXBase.HTMLAttributes<HTMLInsTimepickerElement>;
      'ins-timezone': LocalJSX.InsTimezone & JSXBase.HTMLAttributes<HTMLInsTimezoneElement>;
      'ins-title': LocalJSX.InsTitle & JSXBase.HTMLAttributes<HTMLInsTitleElement>;
      'ins-toggle-switch': LocalJSX.InsToggleSwitch & JSXBase.HTMLAttributes<HTMLInsToggleSwitchElement>;
      'ins-tooltip': LocalJSX.InsTooltip & JSXBase.HTMLAttributes<HTMLInsTooltipElement>;
    }
  }
}


